#![cfg(target_os = "linux")]
#![allow(unsafe_code)] // host-glibc tow* oracle for offline table generation

//! GENERATOR (`#[ignore]`): emits glibc-exact `towupper`/`towlower` delta tables
//! by sweeping the host glibc `towupper(3)`/`towlower(3)` over every Unicode
//! scalar value under a UTF-8 locale and recording only the code points whose
//! mapping differs from the identity. Run on demand with
//! `cargo test -p frankenlibc-abi --test towcase_table_gen -- --ignored --nocapture`,
//! then paste the emitted blocks into
//! `frankenlibc-core/src/string/towcase_table.rs`. Same offline-table-generation
//! pattern as the wcwidth (bd-2g7oyh.194) and wctype (bd-2g7oyh.254) tables; the
//! runtime stays 100% safe Rust (a binary search over the deltas). This replaces
//! the former Rust `char::to_uppercase`/`to_lowercase` mappings plus hand-coded
//! override/version-skew patch tables, which were coupled to Rust's Unicode
//! version. See bd-2g7oyh.254 follow-up.

unsafe extern "C" {
    fn setlocale(category: libc::c_int, locale: *const libc::c_char) -> *mut libc::c_char;
    fn towupper(wc: u32) -> u32;
    fn towlower(wc: u32) -> u32;
}

fn emit(name: &str, deltas: &[(u32, u32)], s: &mut String) {
    s.push_str(&format!(
        "pub(crate) static {name}: [(u32, u32); {}] = [\n",
        deltas.len()
    ));
    for chunk in deltas.chunks(6) {
        s.push_str("    ");
        for (k, v) in chunk {
            s.push_str(&format!("({k:#x},{v:#x}),"));
        }
        s.push('\n');
    }
    s.push_str("];\n");
}

#[test]
#[ignore = "offline generator for the towcase tables (bd-2g7oyh.254 follow-up); run with --ignored --nocapture"]
fn towcase_table_gen() {
    unsafe {
        std::env::set_var("LC_ALL", "C.UTF-8");
        let loc = std::ffi::CString::new("").unwrap();
        if setlocale(libc::LC_ALL, loc.as_ptr()).is_null() {
            std::env::set_var("LC_ALL", "en_US.UTF-8");
            setlocale(libc::LC_ALL, loc.as_ptr());
        }
    }

    let mut upper: Vec<(u32, u32)> = Vec::new();
    let mut lower: Vec<(u32, u32)> = Vec::new();
    for cp in 0u32..=0x10FFFF {
        if (0xD800..=0xDFFF).contains(&cp) {
            continue; // surrogates are not scalar values
        }
        let u = unsafe { towupper(cp) };
        if u != cp {
            upper.push((cp, u));
        }
        let l = unsafe { towlower(cp) };
        if l != cp {
            lower.push((cp, l));
        }
    }

    eprintln!("TOWCASE_GEN upper={} lower={}", upper.len(), lower.len());
    let mut s = String::new();
    s.push_str("// @generated by towcase_table_gen from host glibc towupper/towlower (UTF-8 locale).\n");
    s.push_str("// Each (cp, mapped): tow*(cp) == mapped; code points absent map to themselves.\n");
    emit("TOUPPER_DELTAS", &upper, &mut s);
    s.push('\n');
    emit("TOLOWER_DELTAS", &lower, &mut s);
    eprintln!("TOWCASE_GEN_BEGIN");
    eprint!("{s}");
    eprintln!("TOWCASE_GEN_END");
}
