#![cfg(target_os = "linux")]
#![allow(unsafe_code)] // host-glibc isw* oracle for offline table generation

//! GENERATOR (`#[ignore]`): emits a complete, glibc-exact wide-ctype class table
//! as run-length-encoded transitions of a 12-bit class mask, by sweeping the
//! host glibc `iswalnum`/`iswalpha`/`iswblank`/`iswcntrl`/`iswdigit`/`iswgraph`/
//! `iswlower`/`iswprint`/`iswpunct`/`iswspace`/`iswupper`/`iswxdigit` over every
//! Unicode scalar value under a UTF-8 locale. Run on demand with
//! `cargo test -p frankenlibc-abi --test wctype_table_gen -- --ignored --nocapture`,
//! then paste the emitted `CTYPE_TRANSITIONS` block into
//! `frankenlibc-core/src/string/wctype_table.rs`. Same offline-table-generation
//! pattern as the wcwidth table (bd-2g7oyh.194); the runtime stays 100% safe
//! Rust (a binary search over the table). See bd-2g7oyh.254.

unsafe extern "C" {
    fn setlocale(category: libc::c_int, locale: *const libc::c_char) -> *mut libc::c_char;
    fn iswalnum(wc: u32) -> libc::c_int;
    fn iswalpha(wc: u32) -> libc::c_int;
    fn iswblank(wc: u32) -> libc::c_int;
    fn iswcntrl(wc: u32) -> libc::c_int;
    fn iswdigit(wc: u32) -> libc::c_int;
    fn iswgraph(wc: u32) -> libc::c_int;
    fn iswlower(wc: u32) -> libc::c_int;
    fn iswprint(wc: u32) -> libc::c_int;
    fn iswpunct(wc: u32) -> libc::c_int;
    fn iswspace(wc: u32) -> libc::c_int;
    fn iswupper(wc: u32) -> libc::c_int;
    fn iswxdigit(wc: u32) -> libc::c_int;
}

// Bit positions MUST match frankenlibc_core::string::wctype_table.
const ALNUM: u16 = 1 << 0;
const ALPHA: u16 = 1 << 1;
const BLANK: u16 = 1 << 2;
const CNTRL: u16 = 1 << 3;
const DIGIT: u16 = 1 << 4;
const GRAPH: u16 = 1 << 5;
const LOWER: u16 = 1 << 6;
const PRINT: u16 = 1 << 7;
const PUNCT: u16 = 1 << 8;
const SPACE: u16 = 1 << 9;
const UPPER: u16 = 1 << 10;
const XDIGIT: u16 = 1 << 11;

fn mask_of(cp: u32) -> u16 {
    let w = cp as u32;
    let mut m = 0u16;
    unsafe {
        if iswalnum(w) != 0 {
            m |= ALNUM;
        }
        if iswalpha(w) != 0 {
            m |= ALPHA;
        }
        if iswblank(w) != 0 {
            m |= BLANK;
        }
        if iswcntrl(w) != 0 {
            m |= CNTRL;
        }
        if iswdigit(w) != 0 {
            m |= DIGIT;
        }
        if iswgraph(w) != 0 {
            m |= GRAPH;
        }
        if iswlower(w) != 0 {
            m |= LOWER;
        }
        if iswprint(w) != 0 {
            m |= PRINT;
        }
        if iswpunct(w) != 0 {
            m |= PUNCT;
        }
        if iswspace(w) != 0 {
            m |= SPACE;
        }
        if iswupper(w) != 0 {
            m |= UPPER;
        }
        if iswxdigit(w) != 0 {
            m |= XDIGIT;
        }
    }
    m
}

#[test]
#[ignore = "offline generator for the wide-ctype table (bd-2g7oyh.254); run with --ignored --nocapture"]
fn wctype_table_gen() {
    unsafe {
        std::env::set_var("LC_ALL", "C.UTF-8");
        let loc = std::ffi::CString::new("").unwrap();
        if setlocale(libc::LC_ALL, loc.as_ptr()).is_null() {
            std::env::set_var("LC_ALL", "en_US.UTF-8");
            setlocale(libc::LC_ALL, loc.as_ptr());
        }
    }

    // Run-length encode: a transition (cp, mask) means the class mask equals
    // `mask` for every codepoint in [cp, next_entry.cp). Covers 0..=0x10FFFF.
    let mut transitions: Vec<(u32, u16)> = Vec::new();
    let mut prev = u16::MAX;
    for cp in 0u32..=0x10FFFF {
        let m = mask_of(cp);
        if m != prev {
            transitions.push((cp, m));
            prev = m;
        }
    }

    eprintln!("WCTYPE_GEN transitions={}", transitions.len());
    let mut s = String::new();
    s.push_str("// @generated by wctype_table_gen from host glibc isw* (UTF-8 locale).\n");
    s.push_str("// Each (start, mask): class mask == mask for cp in [start, next_start).\n");
    s.push_str(&format!(
        "pub(crate) static CTYPE_TRANSITIONS: [(u32, u16); {}] = [\n",
        transitions.len()
    ));
    for chunk in transitions.chunks(8) {
        s.push_str("    ");
        for (cp, m) in chunk {
            s.push_str(&format!("({cp:#x},{m:#x}),"));
        }
        s.push('\n');
    }
    s.push_str("];\n");
    eprintln!("WCTYPE_GEN_BEGIN");
    eprint!("{s}");
    eprintln!("WCTYPE_GEN_END");
}
