#![cfg(target_os = "linux")]
#![allow(unsafe_code)] // host-glibc wcwidth oracle for offline table generation

//! GENERATOR (`#[ignore]`): emits a complete, glibc-exact `wcwidth` width table
//! as run-length-encoded transitions, by sweeping the host glibc `wcwidth(3)`
//! over every Unicode scalar value under a UTF-8 locale. Run on demand with
//! `cargo test -- --ignored wcwidth_table_gen --nocapture`, then paste the
//! emitted `WIDTH_TRANSITIONS` block into the generated table module. This is
//! the same offline-table-generation pattern used for the log2 / codepage
//! tables — the runtime stays 100% safe Rust (a binary search over the table).
//! See bd-2g7oyh.194.

unsafe extern "C" {
    fn wcwidth(c: libc::wchar_t) -> libc::c_int;
    fn setlocale(category: libc::c_int, locale: *const libc::c_char) -> *mut libc::c_char;
}

#[test]
#[ignore = "offline generator for the wcwidth table (bd-2g7oyh.194); run with --ignored --nocapture"]
fn wcwidth_table_gen() {
    unsafe {
        std::env::set_var("LC_ALL", "C.UTF-8");
        let loc = std::ffi::CString::new("").unwrap();
        if setlocale(libc::LC_ALL, loc.as_ptr()).is_null() {
            std::env::set_var("LC_ALL", "en_US.UTF-8");
            setlocale(libc::LC_ALL, loc.as_ptr());
        }
    }

    // Run-length encode: a transition entry (cp, w) means wcwidth == w for every
    // codepoint in [cp, next_entry.cp). The table starts at 0 and covers the
    // whole scalar range 0..=0x10FFFF.
    let mut transitions: Vec<(u32, i32)> = Vec::new();
    let mut prev_w = i32::MIN;
    for cp in 0u32..=0x10FFFF {
        let w = unsafe { wcwidth(cp as libc::wchar_t) };
        if w != prev_w {
            transitions.push((cp, w));
            prev_w = w;
        }
    }

    eprintln!("WCWIDTH_GEN transitions={}", transitions.len());
    // Emit as compact Rust source for pasting.
    let mut s = String::new();
    s.push_str("// @generated by wcwidth_table_gen from host glibc wcwidth (UTF-8 locale).\n");
    s.push_str("// Each (start, width): wcwidth == width for cp in [start, next_start).\n");
    s.push_str(&format!(
        "pub(crate) static WIDTH_TRANSITIONS: [(u32, i8); {}] = [\n",
        transitions.len()
    ));
    for chunk in transitions.chunks(8) {
        s.push_str("    ");
        for (cp, w) in chunk {
            s.push_str(&format!("({:#x},{}),", cp, w));
        }
        s.push('\n');
    }
    s.push_str("];\n");
    eprintln!("WCWIDTH_GEN_BEGIN");
    eprint!("{s}");
    eprintln!("WCWIDTH_GEN_END");
}
