#![cfg(target_os = "linux")]
#![allow(unsafe_code)] // host-glibc wcwidth oracle

//! Full-range parity gate: fl `wcwidth` vs host glibc `wcwidth` under a UTF-8
//! locale, over EVERY Unicode scalar value. fl's `wcwidth` is now driven by a
//! glibc-derived run-length table (string/wcwidth_table.rs, generated by the
//! `wcwidth_table_gen` test), so this must be 0 divergences across the whole
//! code space — closing bd-2g7oyh.194 (the former hand-coded list diverged on
//! ~66k codepoints). On a categorized failure, regenerate the table (the host
//! glibc's Unicode version drifted) per wcwidth_table.rs's header.

use std::collections::BTreeMap;

use frankenlibc_core::string::wchar as flc;

unsafe extern "C" {
    fn wcwidth(c: libc::wchar_t) -> libc::c_int;
    fn setlocale(category: libc::c_int, locale: *const libc::c_char) -> *mut libc::c_char;
}

#[test]
fn wcwidth_full_range_matches_glibc() {
    // Seed + activate a UTF-8 locale so glibc consults its width tables.
    unsafe {
        std::env::set_var("LC_ALL", "C.UTF-8");
        let loc = std::ffi::CString::new("").unwrap();
        let r = setlocale(libc::LC_ALL, loc.as_ptr());
        if r.is_null() {
            // Fall back to en_US.UTF-8 if C.UTF-8 isn't present.
            std::env::set_var("LC_ALL", "en_US.UTF-8");
            setlocale(libc::LC_ALL, loc.as_ptr());
        }
    }

    let mut total = 0u64;
    let mut diffs = 0u64;
    // Key: (fl_value, glibc_value) -> count, with a few sample codepoints.
    let mut buckets: BTreeMap<(i32, i32), (u64, Vec<u32>)> = BTreeMap::new();

    let sweep = |lo: u32, hi: u32, total: &mut u64, diffs: &mut u64, buckets: &mut BTreeMap<(i32, i32), (u64, Vec<u32>)>| {
        for cp in lo..=hi {
            // Skip surrogates (not valid scalar values).
            if (0xD800..=0xDFFF).contains(&cp) {
                continue;
            }
            let fl_v = flc::wcwidth(cp);
            let gl_v = unsafe { wcwidth(cp as libc::wchar_t) };
            *total += 1;
            if fl_v != gl_v {
                *diffs += 1;
                let e = buckets.entry((fl_v, gl_v)).or_insert((0, Vec::new()));
                e.0 += 1;
                if e.1.len() < 8 {
                    e.1.push(cp);
                }
            }
        }
    };

    sweep(0x0000, 0x10FFFF, &mut total, &mut diffs, &mut buckets); // entire scalar range

    let mut report = String::new();
    for ((fl_v, gl_v), (count, samples)) in &buckets {
        let s: Vec<String> = samples.iter().map(|c| format!("U+{c:04X}")).collect();
        report.push_str(&format!(
            "  fl={fl_v:>2} glibc={gl_v:>2}  -> {count:>6}  [{}]\n",
            s.join(" ")
        ));
    }
    assert_eq!(
        diffs, 0,
        "wcwidth diverged from host glibc on {diffs}/{total} codepoints \
         (regenerate the table if glibc's Unicode version drifted):\n{report}"
    );
    eprintln!("wcwidth full-range parity: {total} codepoints, 0 divergences vs host glibc");
}
