//! Tables for the CORE-MATH tgamma/lgamma kernels in `coremath.rs`, auto-extracted
//! from CORE-MATH src/binary64/{tgamma/tgamma.c, lgamma/lgamma.c}, the code glibc
//! 2.43 ships. Copyright (c) 2024-2025 Alexei Sibidanov, MIT licence (see
//! `coremath.rs`). Generated by exact hex-float conversion; do not hand-edit.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

/// tgamma.c as_tgamma_database (x, h, l), sorted by x.
pub(crate) const TG_DB: [[f64; 3]; 57] = [
    [
        f64::from_bits(0xc0648ba8e27d09ad),
        f64::from_bits(0x82f0b34f909c5c92),
        f64::from_bits(0x0000100000000000),
    ],
    [
        f64::from_bits(0xc061fe464bbe8b7a),
        f64::from_bits(0x0c5f6e94380a86bf),
        f64::from_bits(0x08f0000000000000),
    ],
    [
        f64::from_bits(0xc05dfe438a574b34),
        f64::from_bits(0x16fe0efc1ffa409e),
        f64::from_bits(0x1390000000000000),
    ],
    [
        f64::from_bits(0xc05c008ed7e2be92),
        f64::from_bits(0x9a82820dd1286d5e),
        f64::from_bits(0x9720000000000000),
    ],
    [
        f64::from_bits(0xc05bcc2b6af0ebae),
        f64::from_bits(0x1a95742e6ca2fe43),
        f64::from_bits(0x9730000000000000),
    ],
    [
        f64::from_bits(0xc052c0358d14dace),
        f64::from_bits(0x29bc8e82e0e0a4f6),
        f64::from_bits(0x2650000000000000),
    ],
    [
        f64::from_bits(0xc04f126edde91b5b),
        f64::from_bits(0xae4f4cdd1a52b2e3),
        f64::from_bits(0xaae0000000000000),
    ],
    [
        f64::from_bits(0xc04d97de88bda2df),
        f64::from_bits(0x2f62227eb4f08b21),
        f64::from_bits(0x2c00000000000000),
    ],
    [
        f64::from_bits(0xc04ce749a6427fdd),
        f64::from_bits(0x2fe30d786820381f),
        f64::from_bits(0xac80000000000000),
    ],
    [
        f64::from_bits(0xc04ccb10c3d47943),
        f64::from_bits(0x2feb9e53a96c9939),
        f64::from_bits(0xac80000000000000),
    ],
    [
        f64::from_bits(0xc04c9cc11aba9632),
        f64::from_bits(0x301644a102fa86b0),
        f64::from_bits(0x2cb0000000000000),
    ],
    [
        f64::from_bits(0xc04b93b0669b1556),
        f64::from_bits(0x30e03a95aab1bc81),
        f64::from_bits(0x2d80000000000000),
    ],
    [
        f64::from_bits(0xc0467893c596ef0c),
        f64::from_bits(0xb491bd662d0bc936),
        f64::from_bits(0x3130000000000000),
    ],
    [
        f64::from_bits(0xc03ae39c32c36e42),
        f64::from_bits(0xba582b46d1babd86),
        f64::from_bits(0xb6f0000000000000),
    ],
    [
        f64::from_bits(0xc038d5826734a060),
        f64::from_bits(0xbaeae95b301e8bf3),
        f64::from_bits(0x3780000000000000),
    ],
    [
        f64::from_bits(0xc03849b47bda8526),
        f64::from_bits(0xbb08c2973252464c),
        f64::from_bits(0x37a0000000000000),
    ],
    [
        f64::from_bits(0xc030ba2acf2de6b2),
        f64::from_bits(0xbd1ca9739fd7435e),
        f64::from_bits(0xb9b0000000000000),
    ],
    [
        f64::from_bits(0xc02f49bb1a25a54e),
        f64::from_bits(0x3d5fbf8e7755e967),
        f64::from_bits(0x39f0000000000000),
    ],
    [
        f64::from_bits(0xc029057ede749837),
        f64::from_bits(0xbe1eb68bf9d04126),
        f64::from_bits(0x3ab0000000000000),
    ],
    [
        f64::from_bits(0xc0265509f6aed026),
        f64::from_bits(0x3e7c3791f14051e1),
        f64::from_bits(0x3b10000000000000),
    ],
    [
        f64::from_bits(0xc025f353a2d26238),
        f64::from_bits(0xbeb20e6a9093e033),
        f64::from_bits(0x3b50000000000000),
    ],
    [
        f64::from_bits(0xc023be29766cccac),
        f64::from_bits(0x3ec8fad89ade334b),
        f64::from_bits(0x3b60000000000000),
    ],
    [
        f64::from_bits(0xc01e33cfdfb73bcd),
        f64::from_bits(0x3f2abe0430abe7de),
        f64::from_bits(0xbbc0000000000000),
    ],
    [
        f64::from_bits(0xc01e11a9d07e14aa),
        f64::from_bits(0x3f2c58ee82102e50),
        f64::from_bits(0x3bc0000000000000),
    ],
    [
        f64::from_bits(0xc019945148859d80),
        f64::from_bits(0xbf61d4187d2d1e32),
        f64::from_bits(0x3c00000000000000),
    ],
    [
        f64::from_bits(0xc013fc07c80057fd),
        f64::from_bits(0xc0014fd6b28fb843),
        f64::from_bits(0xbca0000000000000),
    ],
    [
        f64::from_bits(0xc00ca5042fd026be),
        f64::from_bits(0x3fcfe72b07f8530a),
        f64::from_bits(0x3c60000000000000),
    ],
    [
        f64::from_bits(0xc004f977a4a186e9),
        f64::from_bits(0xbfec7082ecde156a),
        f64::from_bits(0xbc80000000000000),
    ],
    [
        f64::from_bits(0xc002db99b79dfe45),
        f64::from_bits(0xbff394da6c1b5e01),
        f64::from_bits(0x3c90000000000000),
    ],
    [
        f64::from_bits(0xbffd71c18bba5e34),
        f64::from_bits(0x400e1e710f476c6b),
        f64::from_bits(0x3ca0000000000000),
    ],
    [
        f64::from_bits(0xbff9b4cf5c6b37ed),
        f64::from_bits(0x400285a86b08aca2),
        f64::from_bits(0x3ca0000000000000),
    ],
    [
        f64::from_bits(0xbff4c20c91b866ff),
        f64::from_bits(0x400ad49175ae3fa8),
        f64::from_bits(0x3ca0000000000000),
    ],
    [
        f64::from_bits(0xbff3dea2db193059),
        f64::from_bits(0x40102d76ec3da035),
        f64::from_bits(0xbcb0000000000000),
    ],
    [
        f64::from_bits(0xbff2147794f4b43b),
        f64::from_bits(0x401dcaa532ea5c3b),
        f64::from_bits(0xbcb0000000000000),
    ],
    [
        f64::from_bits(0xbfef4180137777f0),
        f64::from_bits(0xc045bab35ff72e22),
        f64::from_bits(0xbce0000000000000),
    ],
    [
        f64::from_bits(0xbfe89c1327cd62e6),
        f64::from_bits(0xc01481a01786e770),
        f64::from_bits(0x3cb0000000000000),
    ],
    [
        f64::from_bits(0xbfe74a9509402866),
        f64::from_bits(0xc012378573c2914e),
        f64::from_bits(0x3cb0000000000000),
    ],
    [
        f64::from_bits(0xbfe0aa724e38e0c9),
        f64::from_bits(0xc00c648650a45953),
        f64::from_bits(0x3ca0000000000000),
    ],
    [
        f64::from_bits(0xbfdee9a5ac162dc1),
        f64::from_bits(0xc00c69d8a8fa985e),
        f64::from_bits(0x3ca0000000000000),
    ],
    [
        f64::from_bits(0xbfdde31773767db1),
        f64::from_bits(0xc00c883c55f5d3a2),
        f64::from_bits(0xbca0000000000000),
    ],
    [
        f64::from_bits(0xbfd0e17b51a5c1cb),
        f64::from_bits(0xc012de378f77ff2d),
        f64::from_bits(0x3cb0000000000000),
    ],
    [
        f64::from_bits(0x3fdc05aa42cb27fe),
        f64::from_bits(0x40002f80f15c9486),
        f64::from_bits(0x3ca0000000000000),
    ],
    [
        f64::from_bits(0x3fe38828fbbe1340),
        f64::from_bits(0x3ff774353be6bfa6),
        f64::from_bits(0xbc90000000000000),
    ],
    [
        f64::from_bits(0x3fe5f35406cd1260),
        f64::from_bits(0x3ff522440edb9679),
        f64::from_bits(0xbc90000000000000),
    ],
    [
        f64::from_bits(0x3ff09ef8f46ee74b),
        f64::from_bits(0x3fef5443da4bc3be),
        f64::from_bits(0xbc80000000000000),
    ],
    [
        f64::from_bits(0x3ff0a9070c11f0c7),
        f64::from_bits(0x3fef4a2abf00601a),
        f64::from_bits(0xbc80000000000000),
    ],
    [
        f64::from_bits(0x3ff94fcb07ab7f61),
        f64::from_bits(0x3fec88182e08d193),
        f64::from_bits(0xbc80000000000000),
    ],
    [
        f64::from_bits(0x3ffbca8ea6404514),
        f64::from_bits(0x3fed512dc4822b38),
        f64::from_bits(0xbc80000000000000),
    ],
    [
        f64::from_bits(0x3ffe0c9a45452d7c),
        f64::from_bits(0x3fee8acd192e461e),
        f64::from_bits(0x3c80000000000000),
    ],
    [
        f64::from_bits(0x400616cd9ea484ab),
        f64::from_bits(0x3ff9f85cce39e731),
        f64::from_bits(0x3c90000000000000),
    ],
    [
        f64::from_bits(0x401a1d899263d9a1),
        f64::from_bits(0x4072f2fb8e4d1274),
        f64::from_bits(0x3d10000000000000),
    ],
    [
        f64::from_bits(0x401b163c719149af),
        f64::from_bits(0x407d76e1ede08821),
        f64::from_bits(0xbd10000000000000),
    ],
    [
        f64::from_bits(0x40543714b74fe055),
        f64::from_bits(0x588ecc3784ce1ff0),
        f64::from_bits(0x5520000000000000),
    ],
    [
        f64::from_bits(0x405676921a72fecf),
        f64::from_bits(0x5c276e0e21ee3989),
        f64::from_bits(0x58c0000000000000),
    ],
    [
        f64::from_bits(0x405f3505ba057812),
        f64::from_bits(0x6ae068712884fb42),
        f64::from_bits(0x6780000000000000),
    ],
    [
        f64::from_bits(0x406303ed951d4340),
        f64::from_bits(0x76ffb70d4503e49b),
        f64::from_bits(0xf390000000000000),
    ],
    [
        f64::from_bits(0x4063a0b358e9e93b),
        f64::from_bits(0x79381a5fa517374f),
        f64::from_bits(0x75d0000000000000),
    ],
];

/// tgamma.c as_tgamma_accurate |x| < 1/4: double-double coefficients.
pub(crate) const TG_ACC0_CC: [[f64; 2]; 28] = [
    [
        f64::from_bits(0xbfe2788cfc6fb619),
        f64::from_bits(0x3c56cb90701fbfba),
    ],
    [
        f64::from_bits(0x3fefa658c23b1578),
        f64::from_bits(0x3c8dd92b465a81dd),
    ],
    [
        f64::from_bits(0xbfed0a118f324b63),
        f64::from_bits(0x3c53a4f48373c073),
    ],
    [
        f64::from_bits(0x3fef6a51055096b5),
        f64::from_bits(0x3c7fabe4f73da654),
    ],
    [
        f64::from_bits(0xbfef6c80ec38b67b),
        f64::from_bits(0x3c8c9fc797e7567e),
    ],
    [
        f64::from_bits(0x3fefc7e0a6eb310b),
        f64::from_bits(0xbc5042340fb21e2f),
    ],
    [
        f64::from_bits(0xbfefdf3f157b7a39),
        f64::from_bits(0xbc86fd12a61ae3a9),
    ],
    [
        f64::from_bits(0x3feff07b5a17ff6c),
        f64::from_bits(0xbc89b8f7ad70e4bc),
    ],
    [
        f64::from_bits(0xbfeff803d68a0bd4),
        f64::from_bits(0x3c4ed4f2b2dcc156),
    ],
    [
        f64::from_bits(0x3feffc0841d585a3),
        f64::from_bits(0xbc87089ffbe760f0),
    ],
    [
        f64::from_bits(0xbfeffe018c484f48),
        f64::from_bits(0x3c8f8a632e2ff912),
    ],
    [
        f64::from_bits(0x3fefff00b768f1c4),
        f64::from_bits(0x3c750de70bb4e28b),
    ],
    [
        f64::from_bits(0xbfefff8035584df4),
        f64::from_bits(0xbc8aae8f6d8b868d),
    ],
    [
        f64::from_bits(0x3fefffc012f95019),
        f64::from_bits(0x3c8d26498825213d),
    ],
    [
        f64::from_bits(0xbfefffe0062afaf7),
        f64::from_bits(0x3c8ef9359641ed4b),
    ],
    [
        f64::from_bits(0x3feffff002146fec),
        f64::from_bits(0x3c81ce6548eaa3c0),
    ],
    [
        f64::from_bits(0xbfeffff800af4ca8),
        f64::from_bits(0x3c767121c2223cb7),
    ],
    [
        f64::from_bits(0x3feffffc0037a50d),
        f64::from_bits(0xbc67c2694e8ff6af),
    ],
    [
        f64::from_bits(0xbfeffffe00676ecc),
        f64::from_bits(0xbc82563151dfa334),
    ],
    [
        f64::from_bits(0x3fefffff00ac53bf),
        f64::from_bits(0x3c83effd975c6fec),
    ],
    [
        f64::from_bits(0xbfefffff72b5b5d1),
        f64::from_bits(0x3c8fb25bd33b12e8),
    ],
    [
        f64::from_bits(0x3fefffffa828c9f3),
        f64::from_bits(0x3c85fde8ff2fb275),
    ],
    [
        f64::from_bits(0xbff00000bc9c338d),
        f64::from_bits(0xbc77ced37913c915),
    ],
    [
        f64::from_bits(0x3ff000014750b54c),
        f64::from_bits(0x3c9980564dfb043c),
    ],
    [
        f64::from_bits(0xbfefffdabf3f1dfb),
        f64::from_bits(0xbc8e34acb3149e71),
    ],
    [
        f64::from_bits(0x3fefffc7cf7439c3),
        f64::from_bits(0xbc82599c887c744a),
    ],
    [
        f64::from_bits(0xbff001452e7ff0b7),
        f64::from_bits(0xbc7acc4a235f0de4),
    ],
    [
        f64::from_bits(0x3ff001c6c5b18192),
        f64::from_bits(0x3c935874aa96ce14),
    ],
];

/// tgamma.c as_tgamma_accurate |x| < 1/4: double coefficients.
pub(crate) const TG_ACC0_C: [f64; 8] = [
    f64::from_bits(0xbfefdf5126e6a83b), // -0x1.fdf5126e6a83bp-1
    f64::from_bits(0x3fefd56c1b531709), // 0x1.fd56c1b531709p-1
    f64::from_bits(0xbff0956741759e58), // -0x1.0956741759e58p+0
    f64::from_bits(0x3ff0b6167d27c5c4), // 0x1.0b6167d27c5c4p+0
    f64::from_bits(0xbfe8e69e55b6dca0), // -0x1.8e69e55b6dca0p-1
    f64::from_bits(0x3fe7e124660c827d), // 0x1.7e124660c827dp-1
    f64::from_bits(0xbffc797b42bd6745), // -0x1.c797b42bd6745p+0
    f64::from_bits(0x3ffd688bb8db046c), // 0x1.d688bb8db046cp+0
];

/// tgamma.c as_tgamma_accurate band ending at 160: leading coefficients.
pub(crate) const TG_ACC_CH160: [f64; 14] = [
    f64::from_bits(0x3ff0079000000000), // 0x1.0079000000000p+0
    f64::from_bits(0x4004569000000000), // 0x1.4569000000000p+1
    f64::from_bits(0x4009cfb000000000), // 0x1.9cfb000000000p+1
    f64::from_bits(0x4005d7e800000000), // 0x1.5d7e800000000p+1
    f64::from_bits(0x3ffbbc2000000000), // 0x1.bbc2000000000p+0
    f64::from_bits(0x3fec2de000000000), // 0x1.c2de000000000p-1
    f64::from_bits(0x3fd7dd4000000000), // 0x1.7dd4000000000p-2
    f64::from_bits(0x3fc1540000000000), // 0x1.1540000000000p-3
    f64::from_bits(0x3fa6060000000000), // 0x1.6060000000000p-5
    f64::from_bits(0x3f88e00000000000), // 0x1.8e00000000000p-7
    f64::from_bits(0x3f69600000000000), // 0x1.9600000000000p-9
    f64::from_bits(0x3f47800000000000), // 0x1.7800000000000p-11
    f64::from_bits(0x3f24000000000000), // 0x1.4000000000000p-13
    f64::from_bits(0x3f00000000000000), // 0x1.0000000000000p-15
];

/// tgamma.c as_tgamma_accurate band ending at 160: double-double tail.
pub(crate) const TG_ACC_CL160: [[f64; 2]; 34] = [
    [
        f64::from_bits(0xbe835efdada260f0),
        f64::from_bits(0xbb28f77d4b23a815),
    ],
    [
        f64::from_bits(0x3ed7df9be2dd4bfe),
        f64::from_bits(0xbb757dcebb38b14a),
    ],
    [
        f64::from_bits(0xbedf2ea2f115251d),
        f64::from_bits(0x3b75db7a1637f6f9),
    ],
    [
        f64::from_bits(0xbedba2ee68beb692),
        f64::from_bits(0xbb6379a1eea94b56),
    ],
    [
        f64::from_bits(0xbec453a3cbf93b46),
        f64::from_bits(0xbb5caedf955a404f),
    ],
    [
        f64::from_bits(0xbed0705e77cba500),
        f64::from_bits(0x3b77c27c7f017abb),
    ],
    [
        f64::from_bits(0x3ec85047ccb18f1e),
        f64::from_bits(0x3b648c618ef405c2),
    ],
    [
        f64::from_bits(0xbed7af537fc58007),
        f64::from_bits(0xbb4b513687e96fb8),
    ],
    [
        f64::from_bits(0xbec6b0d2669b1e53),
        f64::from_bits(0x3b6818f0e8415250),
    ],
    [
        f64::from_bits(0x3ed3ffea7715e965),
        f64::from_bits(0x3b76db8e88404f0a),
    ],
    [
        f64::from_bits(0xbedf63410ae5ac04),
        f64::from_bits(0x3b5e58afac170173),
    ],
    [
        f64::from_bits(0xbec5d6da3bdb1b14),
        f64::from_bits(0xbb33b475b11ba7a4),
    ],
    [
        f64::from_bits(0xbeb22c3a134bb9e5),
        f64::from_bits(0xbb2fac524517c258),
    ],
    [
        f64::from_bits(0xbeacd01e4fcf1000),
        f64::from_bits(0xbb393b7c28c25e10),
    ],
    [
        f64::from_bits(0x3ed69e4ebf3e520a),
        f64::from_bits(0x3b6c8120c75b1cd4),
    ],
    [
        f64::from_bits(0x3eaeb6d0cfb27c49),
        f64::from_bits(0xbb41ecce3a7c4930),
    ],
    [
        f64::from_bits(0x3e838e164032e836),
        f64::from_bits(0xbb2962783da9a188),
    ],
    [
        f64::from_bits(0x3e5770fa90c60f7a),
        f64::from_bits(0x3af5d7127e890bc4),
    ],
    [
        f64::from_bits(0x3e2a8b8bd80a645d),
        f64::from_bits(0xbac74eeaf30435a1),
    ],
    [
        f64::from_bits(0x3dfc7c03bc5e8d14),
        f64::from_bits(0x3a92c25a03df992a),
    ],
    [
        f64::from_bits(0x3dcd0b4225377931),
        f64::from_bits(0x3a3ddb1297fb3cc9),
    ],
    [
        f64::from_bits(0x3d9c35fd7323a155),
        f64::from_bits(0x3a3d4774c8e26f90),
    ],
    [
        f64::from_bits(0x3d6a298bcbc155fa),
        f64::from_bits(0xba0650026f575bee),
    ],
    [
        f64::from_bits(0x3d373684debaa9f6),
        f64::from_bits(0x39d58d03f212eaec),
    ],
    [
        f64::from_bits(0x3d03be174b363d46),
        f64::from_bits(0x3988a28d3d4b2148),
    ],
    [
        f64::from_bits(0x3cd01f81326f4e6b),
        f64::from_bits(0xb9591908a55064f3),
    ],
    [
        f64::from_bits(0x3c9953cbad515517),
        f64::from_bits(0xb92420ffc1db04c7),
    ],
    [
        f64::from_bits(0x3c632925a5ea9c65),
        f64::from_bits(0xb909e94d39e65107),
    ],
    [
        f64::from_bits(0x3c2bf668201467f3),
        f64::from_bits(0x38c56890ec45063c),
    ],
    [
        f64::from_bits(0x3bf3b3c32c75d257),
        f64::from_bits(0x389dfaa5f59e084e),
    ],
    [
        f64::from_bits(0x3bbad258392d239d),
        f64::from_bits(0x385cb0d9ef739c01),
    ],
    [
        f64::from_bits(0x3b81c4de9410ecad),
        f64::from_bits(0x3826792403d59171),
    ],
    [
        f64::from_bits(0x3b47ae04b02dd534),
        f64::from_bits(0x37e93a2496f85817),
    ],
    [
        f64::from_bits(0x3b0acbc408b92b88),
        f64::from_bits(0x37a7ad0987f2e913),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 128: leading coefficients.
pub(crate) const TG_ACC_CH128: [f64; 14] = [
    f64::from_bits(0x3fe9496000000000), // 0x1.9496000000000p-1
    f64::from_bits(0x3ffeac5000000000), // 0x1.eac5000000000p+0
    f64::from_bits(0x40029c0800000000), // 0x1.29c0800000000p+1
    f64::from_bits(0x3ffe1e3000000000), // 0x1.e1e3000000000p+0
    f64::from_bits(0x3ff248f000000000), // 0x1.248f000000000p+0
    f64::from_bits(0x3fe1c46000000000), // 0x1.1c46000000000p-1
    f64::from_bits(0x3fccc88000000000), // 0x1.cc88000000000p-3
    f64::from_bits(0x3fb3fe0000000000), // 0x1.3fe0000000000p-4
    f64::from_bits(0x3f984c0000000000), // 0x1.84c0000000000p-6
    f64::from_bits(0x3f7a400000000000), // 0x1.a400000000000p-8
    f64::from_bits(0x3f59800000000000), // 0x1.9800000000000p-10
    f64::from_bits(0x3f37000000000000), // 0x1.7000000000000p-12
    f64::from_bits(0x3f14000000000000), // 0x1.4000000000000p-14
    f64::from_bits(0x3ef0000000000000), // 0x1.0000000000000p-16
];

/// tgamma.c as_tgamma_accurate band ending at 128: double-double tail.
pub(crate) const TG_ACC_CL128: [[f64; 2]; 33] = [
    [
        f64::from_bits(0x3ed8e707e9176d4e),
        f64::from_bits(0x3b718eb4b2587c6b),
    ],
    [
        f64::from_bits(0x3eac647adb963f23),
        f64::from_bits(0xbb4b26e8986d3017),
    ],
    [
        f64::from_bits(0x3ed6886696cb9659),
        f64::from_bits(0xbb7697ce1c89986f),
    ],
    [
        f64::from_bits(0x3ed16285b78f812a),
        f64::from_bits(0xbb38ee808b24a62b),
    ],
    [
        f64::from_bits(0xbed68335ce0107ea),
        f64::from_bits(0xbb77e002876bc274),
    ],
    [
        f64::from_bits(0x3ec9cb055b4f8942),
        f64::from_bits(0x3b6c94d03e5eb637),
    ],
    [
        f64::from_bits(0xbea4c6bf6842f51d),
        f64::from_bits(0xbb23e43b6edbaaca),
    ],
    [
        f64::from_bits(0xbedc7106a068341f),
        f64::from_bits(0x3b7195285bab5ec2),
    ],
    [
        f64::from_bits(0x3edf5998fe3d915f),
        f64::from_bits(0xbb65948c0e9510eb),
    ],
    [
        f64::from_bits(0x3ed97b0180d0c5f5),
        f64::from_bits(0xbb611410994a517a),
    ],
    [
        f64::from_bits(0x3ed2a21a8d31c72b),
        f64::from_bits(0xbb619ad99344e42d),
    ],
    [
        f64::from_bits(0xbed76ac336149616),
        f64::from_bits(0xbb7e86bde11a9a81),
    ],
    [
        f64::from_bits(0xbeda15f563f0b167),
        f64::from_bits(0x3b636b11fc19411c),
    ],
    [
        f64::from_bits(0xbec1deb5989b9a30),
        f64::from_bits(0xbb6bfdc7707da2ea),
    ],
    [
        f64::from_bits(0x3ec32a52525f4863),
        f64::from_bits(0x3b3f85b217b7d774),
    ],
    [
        f64::from_bits(0x3e98e93c045c1cf8),
        f64::from_bits(0x3b29cad2ac270a72),
    ],
    [
        f64::from_bits(0x3e6e5d8b386f2d64),
        f64::from_bits(0xbae820c77564cd71),
    ],
    [
        f64::from_bits(0x3e416c8506f985d5),
        f64::from_bits(0x3aee7e180d6fac2a),
    ],
    [
        f64::from_bits(0x3e12e41d5e5f0a4b),
        f64::from_bits(0x3ab360871c61556e),
    ],
    [
        f64::from_bits(0x3de368f32a797fba),
        f64::from_bits(0xba687cc8925213b6),
    ],
    [
        f64::from_bits(0x3db2f3b3045158f1),
        f64::from_bits(0xba5b42574ac644aa),
    ],
    [
        f64::from_bits(0x3d81a10f6a02627a),
        f64::from_bits(0xb9c5e6cc913c895b),
    ],
    [
        f64::from_bits(0x3d4f5100472f2101),
        f64::from_bits(0x39de485e076a616b),
    ],
    [
        f64::from_bits(0x3d1a9d3f94b0e784),
        f64::from_bits(0x39b0e407c106b58e),
    ],
    [
        f64::from_bits(0x3ce5aeb873725533),
        f64::from_bits(0x398482c0d148c26b),
    ],
    [
        f64::from_bits(0x3cb0f69e30b483c5),
        f64::from_bits(0x395674f383d8090c),
    ],
    [
        f64::from_bits(0x3c79879f300bf8a1),
        f64::from_bits(0xb8e19ca77e2fe1e5),
    ],
    [
        f64::from_bits(0x3c42816bf4968093),
        f64::from_bits(0xb8ec16acd78f35e5),
    ],
    [
        f64::from_bits(0x3c09dffd9c4fa0d7),
        f64::from_bits(0xb89b4280170f91a4),
    ],
    [
        f64::from_bits(0x3bd1751481bc6761),
        f64::from_bits(0xb86d0b5cdc9e8b59),
    ],
    [
        f64::from_bits(0x3b96e40af3edb3b8),
        f64::from_bits(0x3813da803a35bf4c),
    ],
    [
        f64::from_bits(0x3b5e1e8285879a4d),
        f64::from_bits(0xb7ee0ba5a096ee05),
    ],
    [
        f64::from_bits(0x3b20ec77abc3346a),
        f64::from_bits(0xb7cac5f2c2aa6632),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 96: leading coefficients.
pub(crate) const TG_ACC_CH96: [f64; 13] = [
    f64::from_bits(0x3fef9ee000000000), // 0x1.f9ee000000000p-1
    f64::from_bits(0x40020a8000000000), // 0x1.20a8000000000p+1
    f64::from_bits(0x400498c000000000), // 0x1.498c000000000p+1
    f64::from_bits(0x3fff5e4000000000), // 0x1.f5e4000000000p+0
    f64::from_bits(0x3ff1ec7000000000), // 0x1.1ec7000000000p+0
    f64::from_bits(0x3fe0650000000000), // 0x1.0650000000000p-1
    f64::from_bits(0x3fc9018000000000), // 0x1.9018000000000p-3
    f64::from_bits(0x3fb05a0000000000), // 0x1.05a0000000000p-4
    f64::from_bits(0x3f92b80000000000), // 0x1.2b80000000000p-6
    f64::from_bits(0x3f73100000000000), // 0x1.3100000000000p-8
    f64::from_bits(0x3f51800000000000), // 0x1.1800000000000p-10
    f64::from_bits(0x3f2e000000000000), // 0x1.e000000000000p-13
    f64::from_bits(0x3f08000000000000), // 0x1.8000000000000p-15
];

/// tgamma.c as_tgamma_accurate band ending at 96: double-double tail.
pub(crate) const TG_ACC_CL96: [[f64; 2]; 32] = [
    [
        f64::from_bits(0x3ecc78cd57b8f02e),
        f64::from_bits(0xbb58c6c3dfa6aafe),
    ],
    [
        f64::from_bits(0xbea141e76cd562bb),
        f64::from_bits(0xbb37a6effaf310ff),
    ],
    [
        f64::from_bits(0xbe8b3bfffd9645f9),
        f64::from_bits(0x3b1d0be736d9ea75),
    ],
    [
        f64::from_bits(0xbec74a101cbcea97),
        f64::from_bits(0xbb6bd3aa654f0d59),
    ],
    [
        f64::from_bits(0x3ed1f7115750e069),
        f64::from_bits(0xbb595d25b304262a),
    ],
    [
        f64::from_bits(0x3e8b91c47e155385),
        f64::from_bits(0xbb28e4d746fd0075),
    ],
    [
        f64::from_bits(0xbecbb86f8f5c65c2),
        f64::from_bits(0x3b6381bdbd4c1c5b),
    ],
    [
        f64::from_bits(0x3edcd0650618cb0a),
        f64::from_bits(0x3b79688706a3db21),
    ],
    [
        f64::from_bits(0x3edaa7f4480b06b5),
        f64::from_bits(0xbb76db50a59f90bb),
    ],
    [
        f64::from_bits(0x3eb7268062231b9b),
        f64::from_bits(0xbb53fb68176b596f),
    ],
    [
        f64::from_bits(0xbeb04f22e54f0afb),
        f64::from_bits(0x3b4e02ebcb9e86e2),
    ],
    [
        f64::from_bits(0xbedacd49a07fb2b5),
        f64::from_bits(0xbb6309feee83299b),
    ],
    [
        f64::from_bits(0xbecb201681361e3c),
        f64::from_bits(0xbb1159c15b7d4d21),
    ],
    [
        f64::from_bits(0x3edf8279d8aa1d7b),
        f64::from_bits(0xbb698f1053b36c68),
    ],
    [
        f64::from_bits(0x3eb4ad47fe92e846),
        f64::from_bits(0x3b19c7afd69fcdc2),
    ],
    [
        f64::from_bits(0x3e8956f032ef399e),
        f64::from_bits(0xbb2a69375bda764d),
    ],
    [
        f64::from_bits(0x3e5d2072b342925a),
        f64::from_bits(0xbacf392ab37bca41),
    ],
    [
        f64::from_bits(0x3e2f868142b56aa9),
        f64::from_bits(0xbacb6cee9e438fbf),
    ],
    [
        f64::from_bits(0x3e001ede1370ca43),
        f64::from_bits(0x3aaffd62a5b184f4),
    ],
    [
        f64::from_bits(0x3dcf409c99b792a5),
        f64::from_bits(0xba6f2131330468a5),
    ],
    [
        f64::from_bits(0x3d9ccaefeaee2271),
        f64::from_bits(0x3a2c8f2629b8d1f6),
    ],
    [
        f64::from_bits(0x3d694676dbf25420),
        f64::from_bits(0xba093363fe2f6303),
    ],
    [
        f64::from_bits(0x3d35305612768bb2),
        f64::from_bits(0x39b1a5310aba4ab9),
    ],
    [
        f64::from_bits(0x3d00ffa5b925ce6f),
        f64::from_bits(0xb9a37b6a905b0ef1),
    ],
    [
        f64::from_bits(0x3cca2656e8fad62d),
        f64::from_bits(0xb963a327c3656cff),
    ],
    [
        f64::from_bits(0x3c93516bc8a6740d),
        f64::from_bits(0x392414cf70cf8d99),
    ],
    [
        f64::from_bits(0x3c5b7514d20d05f2),
        f64::from_bits(0xb8f716a9bf7fc4df),
    ],
    [
        f64::from_bits(0x3c22cc1700d2e504),
        f64::from_bits(0xb8b48bce98e6490b),
    ],
    [
        f64::from_bits(0x3be8cfd88b5e7cf7),
        f64::from_bits(0xb884a7ab42096b4f),
    ],
    [
        f64::from_bits(0x3bafc50fc5a359f9),
        f64::from_bits(0x384813d73fa7c688),
    ],
    [
        f64::from_bits(0x3b74595e9eb5cd68),
        f64::from_bits(0x37e0cbcc598f3247),
    ],
    [
        f64::from_bits(0x3b367509ddcf771e),
        f64::from_bits(0x37c2afe131ae173d),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 64: leading coefficients.
pub(crate) const TG_ACC_CH64: [f64; 13] = [
    f64::from_bits(0x3fefd48000000000), // 0x1.fd48000000000p-1
    f64::from_bits(0x40008c2000000000), // 0x1.08c2000000000p+1
    f64::from_bits(0x4001386000000000), // 0x1.1386000000000p+1
    f64::from_bits(0x3ff7ea5000000000), // 0x1.7ea5000000000p+0
    f64::from_bits(0x3fe8eea000000000), // 0x1.8eea000000000p-1
    f64::from_bits(0x3fd4d00000000000), // 0x1.4d00000000000p-2
    f64::from_bits(0x3fbcfb0000000000), // 0x1.cfb0000000000p-4
    f64::from_bits(0x3fa1500000000000), // 0x1.1500000000000p-5
    f64::from_bits(0x3f82200000000000), // 0x1.2200000000000p-7
    f64::from_bits(0x3f60e00000000000), // 0x1.0e00000000000p-9
    f64::from_bits(0x3f3c000000000000), // 0x1.c000000000000p-12
    f64::from_bits(0x3f14000000000000), // 0x1.4000000000000p-14
    f64::from_bits(0x3ef0000000000000), // 0x1.0000000000000p-16
];

/// tgamma.c as_tgamma_accurate band ending at 64: double-double tail.
pub(crate) const TG_ACC_CL64: [[f64; 2]; 32] = [
    [
        f64::from_bits(0x3ed5707d010a8f9e),
        f64::from_bits(0x3b31cd385e4fc0f9),
    ],
    [
        f64::from_bits(0xbed58b73a5631c60),
        f64::from_bits(0x3b61d3603c734ffd),
    ],
    [
        f64::from_bits(0xbed3140a3ad6ae57),
        f64::from_bits(0xbb6da8e7c85d715e),
    ],
    [
        f64::from_bits(0x3eb6b0c5338e5384),
        f64::from_bits(0x3b5efc2c921fa207),
    ],
    [
        f64::from_bits(0x3ed824ecd8850473),
        f64::from_bits(0xbb7509b36bf6318f),
    ],
    [
        f64::from_bits(0xbe939fae2bb0a7b8),
        f64::from_bits(0xbb25c1a0cae8774e),
    ],
    [
        f64::from_bits(0x3ec76aadfd438322),
        f64::from_bits(0x3b6045572bdbb76c),
    ],
    [
        f64::from_bits(0xbecf99e20df21f82),
        f64::from_bits(0xbb6e66544233f3bd),
    ],
    [
        f64::from_bits(0xbede66db8450df87),
        f64::from_bits(0xbb7899ca09ee0617),
    ],
    [
        f64::from_bits(0xbec36a70e91aaa64),
        f64::from_bits(0xbb695f52cb796fc7),
    ],
    [
        f64::from_bits(0x3ed0e5fa77b36437),
        f64::from_bits(0x3b7dc1d5188b6ee8),
    ],
    [
        f64::from_bits(0x3ed8f82eddfdf12d),
        f64::from_bits(0x3b1f96b0393cd92e),
    ],
    [
        f64::from_bits(0xbead2517c38f4223),
        f64::from_bits(0x3b3ef82090bb6937),
    ],
    [
        f64::from_bits(0x3ec383219e9f6c6d),
        f64::from_bits(0xbb6d5f4e489d4b4c),
    ],
    [
        f64::from_bits(0x3e9772f83f07674a),
        f64::from_bits(0xbb31078add968846),
    ],
    [
        f64::from_bits(0x3e6a52d1ce181a4c),
        f64::from_bits(0xbb05cfd72cddd6f6),
    ],
    [
        f64::from_bits(0x3e3bb9f07f338f7a),
        f64::from_bits(0x3adf815d2263f4a0),
    ],
    [
        f64::from_bits(0x3e0b8236b99402e9),
        f64::from_bits(0x3aa6ad738311aa1c),
    ],
    [
        f64::from_bits(0x3dd9cc29e9133bec),
        f64::from_bits(0xba7fb04c2e039096),
    ],
    [
        f64::from_bits(0x3da6f02b67c4c01a),
        f64::from_bits(0x3a396ee3d672ff9c),
    ],
    [
        f64::from_bits(0x3d7364416a73a182),
        f64::from_bits(0xba1c471b8d12f423),
    ],
    [
        f64::from_bits(0x3d3f402cfa1d2176),
        f64::from_bits(0xb9d09eb27385e9c1),
    ],
    [
        f64::from_bits(0x3d080e4505fae2a2),
        f64::from_bits(0xb9a89b3ab7c8cfc8),
    ],
    [
        f64::from_bits(0x3cd1b9ee5ece1b68),
        f64::from_bits(0xb9634f81a87fae7e),
    ],
    [
        f64::from_bits(0x3c990e43d92e9cb4),
        f64::from_bits(0x39354bb8ddddd531),
    ],
    [
        f64::from_bits(0x3c61034e7e674987),
        f64::from_bits(0xb90027786f083934),
    ],
    [
        f64::from_bits(0x3c263b88b2da3df3),
        f64::from_bits(0x38b50e6876f58749),
    ],
    [
        f64::from_bits(0x3bebff6e7ec38ee2),
        f64::from_bits(0x388d26042ee70922),
    ],
    [
        f64::from_bits(0x3bb100e634de8248),
        f64::from_bits(0xb85742620952ba9a),
    ],
    [
        f64::from_bits(0x3b74046bb4643d14),
        f64::from_bits(0x377f7bc9779b9709),
    ],
    [
        f64::from_bits(0x3b377deb8521aacf),
        f64::from_bits(0x37d8523ae2540fa8),
    ],
    [
        f64::from_bits(0x3af82bcd04f34df6),
        f64::from_bits(0x3799c7c0c516c99f),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 32: leading coefficients.
pub(crate) const TG_ACC_CH32: [f64; 12] = [
    f64::from_bits(0x3ff1d8e000000000), // 0x1.1d8e000000000p+0
    f64::from_bits(0x3ffeed6000000000), // 0x1.eed6000000000p+0
    f64::from_bits(0x3ffaddd000000000), // 0x1.addd000000000p+0
    f64::from_bits(0x3fef32c000000000), // 0x1.f32c000000000p-1
    f64::from_bits(0x3fdb3d4000000000), // 0x1.b3d4000000000p-2
    f64::from_bits(0x3fc3130000000000), // 0x1.3130000000000p-3
    f64::from_bits(0x3fa6500000000000), // 0x1.6500000000000p-5
    f64::from_bits(0x3f86700000000000), // 0x1.6700000000000p-7
    f64::from_bits(0x3f63c00000000000), // 0x1.3c00000000000p-9
    f64::from_bits(0x3f3f000000000000), // 0x1.f000000000000p-12
    f64::from_bits(0x3f18000000000000), // 0x1.8000000000000p-14
    f64::from_bits(0x3ef0000000000000), // 0x1.0000000000000p-16
];

/// tgamma.c as_tgamma_accurate band ending at 32: double-double tail.
pub(crate) const TG_ACC_CL32: [[f64; 2]; 30] = [
    [
        f64::from_bits(0x3ed08788e5afe5de),
        f64::from_bits(0x3b53ee3cd2a75802),
    ],
    [
        f64::from_bits(0x3ea858860fe7bccb),
        f64::from_bits(0x3b20ceddfcb3586c),
    ],
    [
        f64::from_bits(0xbe8e32f925f74881),
        f64::from_bits(0xbb2c8be268af7c68),
    ],
    [
        f64::from_bits(0xbed9a65ca00dc604),
        f64::from_bits(0x3b73664b3fa1f36e),
    ],
    [
        f64::from_bits(0x3ebc5c11cd8da405),
        f64::from_bits(0xbb5e2437a70d9247),
    ],
    [
        f64::from_bits(0xbed7d49b382dc165),
        f64::from_bits(0x3b769f02bb1656e9),
    ],
    [
        f64::from_bits(0x3ec14365c1b9a8dc),
        f64::from_bits(0xbb564190c0310f4e),
    ],
    [
        f64::from_bits(0xbed264ca62f5b521),
        f64::from_bits(0xbb7d054f7489b23d),
    ],
    [
        f64::from_bits(0x3ec72e83cdc675dc),
        f64::from_bits(0x3b689c0b0a3674dc),
    ],
    [
        f64::from_bits(0x3eaf355500214418),
        f64::from_bits(0x3b2303e6a2bb42aa),
    ],
    [
        f64::from_bits(0xbedfe131bca3fe2e),
        f64::from_bits(0x3b036c088eef6972),
    ],
    [
        f64::from_bits(0xbebcae961f5880f4),
        f64::from_bits(0xbb59b584ebcee700),
    ],
    [
        f64::from_bits(0x3ec0da3a3b8dd7b6),
        f64::from_bits(0x3b6de0818c1103d1),
    ],
    [
        f64::from_bits(0x3e927e24b54f5efc),
        f64::from_bits(0x3b3c16bcb66079d6),
    ],
    [
        f64::from_bits(0x3e62e24b46ea5b9c),
        f64::from_bits(0x3af6ae734aab6297),
    ],
    [
        f64::from_bits(0x3e320948894ade9e),
        f64::from_bits(0xbadce21f3b3e69d3),
    ],
    [
        f64::from_bits(0x3e002f1573b1894f),
        f64::from_bits(0xbaa2885bf7979555),
    ],
    [
        f64::from_bits(0x3dcb6453cc9db81c),
        f64::from_bits(0x3a5b885dc6a6e672),
    ],
    [
        f64::from_bits(0x3d95f01b66699e4f),
        f64::from_bits(0xba386d1947a5527d),
    ],
    [
        f64::from_bits(0x3d60adc466fcfcc4),
        f64::from_bits(0x3a010184dbc0aa14),
    ],
    [
        f64::from_bits(0x3d28240d0955089f),
        f64::from_bits(0xb9c3e1359fb3cb01),
    ],
    [
        f64::from_bits(0x3cf0abe8782bcb76),
        f64::from_bits(0x396898bdd66d4264),
    ],
    [
        f64::from_bits(0x3cb605c88eb0b0e2),
        f64::from_bits(0x394d367940f1eaf7),
    ],
    [
        f64::from_bits(0x3c7be13c09b8cb35),
        f64::from_bits(0x391b0d6934f0969d),
    ],
    [
        f64::from_bits(0x3c40f1bb7e179b3b),
        f64::from_bits(0xb8e4758d0f583b01),
    ],
    [
        f64::from_bits(0x3c03cf0d7e4564b9),
        f64::from_bits(0xb89ab7dacbe5a77c),
    ],
    [
        f64::from_bits(0x3bc64cd2b355bd94),
        f64::from_bits(0x3853300f36dbdb1b),
    ],
    [
        f64::from_bits(0x3b88440addcd6f88),
        f64::from_bits(0xb7d2983c9b95f530),
    ],
    [
        f64::from_bits(0x3b4a288c864c407e),
        f64::from_bits(0x37aeaeadc5c2a302),
    ],
    [
        f64::from_bits(0x3b0936e038d60b53),
        f64::from_bits(0xb7a3364d18a07032),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 26: leading coefficients.
pub(crate) const TG_ACC_CH26: [f64; 12] = [
    f64::from_bits(0x3ff0470000000000), // 0x1.0470000000000p+0
    f64::from_bits(0x3ffa846800000000), // 0x1.a846800000000p+0
    f64::from_bits(0x3ff5ad7000000000), // 0x1.5ad7000000000p+0
    f64::from_bits(0x3fe7b64000000000), // 0x1.7b64000000000p-1
    f64::from_bits(0x3fd3852000000000), // 0x1.3852000000000p-2
    f64::from_bits(0x3fb9cc8000000000), // 0x1.9cc8000000000p-4
    f64::from_bits(0x3f9c820000000000), // 0x1.c820000000000p-6
    f64::from_bits(0x3f7b180000000000), // 0x1.b180000000000p-8
    f64::from_bits(0x3f56a00000000000), // 0x1.6a00000000000p-10
    f64::from_bits(0x3f31000000000000), // 0x1.1000000000000p-12
    f64::from_bits(0x3f08000000000000), // 0x1.8000000000000p-15
    f64::from_bits(0x3ee0000000000000), // 0x1.0000000000000p-17
];

/// tgamma.c as_tgamma_accurate band ending at 26: double-double tail.
pub(crate) const TG_ACC_CL26: [[f64; 2]; 29] = [
    [
        f64::from_bits(0x3eca7b3763fc86d4),
        f64::from_bits(0x3b6f2bfe298eb76d),
    ],
    [
        f64::from_bits(0xbec9edf082edd847),
        f64::from_bits(0xbb4637eef57fb3bc),
    ],
    [
        f64::from_bits(0x3ec1e50c072b2042),
        f64::from_bits(0xbb5b999e1b7bd929),
    ],
    [
        f64::from_bits(0xbea6e1a698fec4bd),
        f64::from_bits(0x3b43e7cf3aa75219),
    ],
    [
        f64::from_bits(0x3ecec7eb3251126e),
        f64::from_bits(0xbb6fccfa136951d6),
    ],
    [
        f64::from_bits(0xbeb75133f02463cc),
        f64::from_bits(0x3b255b27a0ab7fc2),
    ],
    [
        f64::from_bits(0xbe91dde62b18b04c),
        f64::from_bits(0x3b30b84d6dcb215a),
    ],
    [
        f64::from_bits(0xbeb4ce23b6fb3257),
        f64::from_bits(0x3b10b3ec4cc119df),
    ],
    [
        f64::from_bits(0xbebf24694600ef28),
        f64::from_bits(0x3b3a624cef9a725e),
    ],
    [
        f64::from_bits(0xbec90a6a37c3c06d),
        f64::from_bits(0xbb62adc4f450bc1c),
    ],
    [
        f64::from_bits(0xbec6f4bf9bfd39db),
        f64::from_bits(0xbb622773d6af9d2f),
    ],
    [
        f64::from_bits(0xbeb17bbbc341037a),
        f64::from_bits(0xbae5d251c8d425d8),
    ],
    [
        f64::from_bits(0x3eaf1a0eb7f8d730),
        f64::from_bits(0xbb43bcfc3d5e17c3),
    ],
    [
        f64::from_bits(0x3e8034a47489d445),
        f64::from_bits(0xbb2ab4fc357d6378),
    ],
    [
        f64::from_bits(0x3e4f73d5e00b50b9),
        f64::from_bits(0xbad4bc0e702e7c20),
    ],
    [
        f64::from_bits(0x3e1c911b4728cbd3),
        f64::from_bits(0x3a97b2b1db2787a5),
    ],
    [
        f64::from_bits(0x3de8641cdcbb6b73),
        f64::from_bits(0xba87e342f0e64af3),
    ],
    [
        f64::from_bits(0x3db3a74f6feade5b),
        f64::from_bits(0x3a4c4dbbf00254da),
    ],
    [
        f64::from_bits(0x3d7dfe03d3b95b87),
        f64::from_bits(0xba1779af9dd23ca5),
    ],
    [
        f64::from_bits(0x3d45bca6f9345035),
        f64::from_bits(0xb9e9809863c46a40),
    ],
    [
        f64::from_bits(0x3d0e025d291bb213),
        f64::from_bits(0x39886bfdbab2a35b),
    ],
    [
        f64::from_bits(0x3cd3c73ef8cc9fe0),
        f64::from_bits(0xb958487fb03e56bd),
    ],
    [
        f64::from_bits(0x3c98f298b5a16d77),
        f64::from_bits(0x3932d1e9f80d0656),
    ],
    [
        f64::from_bits(0x3c5e2c7aa7139c29),
        f64::from_bits(0xb8f6194ec5ebbc6c),
    ],
    [
        f64::from_bits(0x3c218760ee1fd378),
        f64::from_bits(0x38cb04b22c0b3000),
    ],
    [
        f64::from_bits(0x3be3976787052c12),
        f64::from_bits(0xb8894e76e07a7345),
    ],
    [
        f64::from_bits(0x3ba523d7c6d6d11e),
        f64::from_bits(0xb84f07495c35a672),
    ],
    [
        f64::from_bits(0x3b668e0a8901c32e),
        f64::from_bits(0xb809b92b26f525f1),
    ],
    [
        f64::from_bits(0x3b259a8bf4071da2),
        f64::from_bits(0xb7cded899b17529f),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 16: leading coefficients.
pub(crate) const TG_ACC_CH16: [f64; 11] = [
    f64::from_bits(0x3ff2e19000000000), // 0x1.2e19000000000p+0
    f64::from_bits(0x3ffa2d2000000000), // 0x1.a2d2000000000p+0
    f64::from_bits(0x3ff24ae000000000), // 0x1.24ae000000000p+0
    f64::from_bits(0x3fe12d2000000000), // 0x1.12d2000000000p-1
    f64::from_bits(0x3fc85f0000000000), // 0x1.85f0000000000p-3
    f64::from_bits(0x3fabdc0000000000), // 0x1.bdc0000000000p-5
    f64::from_bits(0x3f8ab80000000000), // 0x1.ab80000000000p-7
    f64::from_bits(0x3f66200000000000), // 0x1.6200000000000p-9
    f64::from_bits(0x3f40000000000000), // 0x1.0000000000000p-11
    f64::from_bits(0x3f14000000000000), // 0x1.4000000000000p-14
    f64::from_bits(0x3ef0000000000000), // 0x1.0000000000000p-16
];

/// tgamma.c as_tgamma_accurate band ending at 16: double-double tail.
pub(crate) const TG_ACC_CL16: [[f64; 2]; 29] = [
    [
        f64::from_bits(0x3e6d0981002b8dcd),
        f64::from_bits(0xbb00ae8574151114),
    ],
    [
        f64::from_bits(0x3ec21706a4d09ab8),
        f64::from_bits(0xbb532b74543eb2be),
    ],
    [
        f64::from_bits(0x3ed3e8095f4cb656),
        f64::from_bits(0x3b7bc796acd28761),
    ],
    [
        f64::from_bits(0x3ed30787fd8e4581),
        f64::from_bits(0xbb5bd47cf783c039),
    ],
    [
        f64::from_bits(0x3ed88d7d37321610),
        f64::from_bits(0xbb720b483cf2643c),
    ],
    [
        f64::from_bits(0x3ed29e7fefe96787),
        f64::from_bits(0xbb7298d41fe9bdcc),
    ],
    [
        f64::from_bits(0x3ec397a3e61f6195),
        f64::from_bits(0x3b64349a3f7a0168),
    ],
    [
        f64::from_bits(0xbeb61f8b334d0636),
        f64::from_bits(0x3b3d10573aa993ac),
    ],
    [
        f64::from_bits(0x3ecd0cf2ec845cf3),
        f64::from_bits(0x3b4fb20051e9ebe6),
    ],
    [
        f64::from_bits(0x3ed000599df4de2b),
        f64::from_bits(0x3b64d947d89b02cb),
    ],
    [
        f64::from_bits(0xbecce4c3c64cf0d2),
        f64::from_bits(0x3b6cc1a5d2dcc154),
    ],
    [
        f64::from_bits(0x3ebab9d3e2c45b3e),
        f64::from_bits(0x3b581ef343d36f1f),
    ],
    [
        f64::from_bits(0x3e8a92575df4eb3b),
        f64::from_bits(0xbb1fb6784e2f7401),
    ],
    [
        f64::from_bits(0x3e58842770eab9c5),
        f64::from_bits(0x3af7b4dc0b29de35),
    ],
    [
        f64::from_bits(0x3e251ce1cfb60d71),
        f64::from_bits(0xbab452ce054d3324),
    ],
    [
        f64::from_bits(0x3df10e17b81bf75e),
        f64::from_bits(0xba969bfe10efa7f7),
    ],
    [
        f64::from_bits(0x3db9f556d989db8b),
        f64::from_bits(0x3a56f1687badbf46),
    ],
    [
        f64::from_bits(0x3d82ae585ff0ac32),
        f64::from_bits(0x3a29d8eaa07598e9),
    ],
    [
        f64::from_bits(0x3d4982eddb5fb2ca),
        f64::from_bits(0xb9ecde9b5613dc57),
    ],
    [
        f64::from_bits(0x3d1093c09caa4734),
        f64::from_bits(0x399fe61a1d516c3e),
    ],
    [
        f64::from_bits(0x3cd48e5fa5f33d0e),
        f64::from_bits(0xb959aca6f48cc057),
    ],
    [
        f64::from_bits(0x3c9861601359014f),
        f64::from_bits(0x393bdbb28174b55b),
    ],
    [
        f64::from_bits(0x3c5bb79265fb1f49),
        f64::from_bits(0x38d9bf33a9bfde0e),
    ],
    [
        f64::from_bits(0x3c1e4376fea4f434),
        f64::from_bits(0xb87a0590b281c112),
    ],
    [
        f64::from_bits(0x3bdfcb050fe822ab),
        f64::from_bits(0x38306b1825b5f657),
    ],
    [
        f64::from_bits(0x3ba0173552d965ef),
        f64::from_bits(0xb7edfebaea36ba1f),
    ],
    [
        f64::from_bits(0x3b5f79f2fdba95fa),
        f64::from_bits(0x37f2387fbe549d20),
    ],
    [
        f64::from_bits(0x3b1e6141ae71b61d),
        f64::from_bits(0xb7be48646743a55a),
    ],
    [
        f64::from_bits(0x3adabf8c29cb5e1f),
        f64::from_bits(0xb74b878f169701f0),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 8: leading coefficients.
pub(crate) const TG_ACC_CH8: [f64; 10] = [
    f64::from_bits(0x3feb693000000000), // 0x1.b693000000000p-1
    f64::from_bits(0x3fec823000000000), // 0x1.c823000000000p-1
    f64::from_bits(0x3fde818000000000), // 0x1.e818000000000p-2
    f64::from_bits(0x3fc64d8000000000), // 0x1.64d8000000000p-3
    f64::from_bits(0x3fa8fe0000000000), // 0x1.8fe0000000000p-5
    f64::from_bits(0x3f86d80000000000), // 0x1.6d80000000000p-7
    f64::from_bits(0x3f61b00000000000), // 0x1.1b00000000000p-9
    f64::from_bits(0x3f38000000000000), // 0x1.8000000000000p-12
    f64::from_bits(0x3f0c000000000000), // 0x1.c000000000000p-15
    f64::from_bits(0x3ee0000000000000), // 0x1.0000000000000p-17
];

/// tgamma.c as_tgamma_accurate band ending at 8: double-double tail.
pub(crate) const TG_ACC_CL8: [[f64; 2]; 28] = [
    [
        f64::from_bits(0x3ec088c57e431647),
        f64::from_bits(0xbb46a4eee248922d),
    ],
    [
        f64::from_bits(0x3ec77c5c5a44df36),
        f64::from_bits(0x3b6147a9a4751800),
    ],
    [
        f64::from_bits(0xbebabecfde1c8f8a),
        f64::from_bits(0x3b5c281ee34fa516),
    ],
    [
        f64::from_bits(0xbec92dc5889bed4b),
        f64::from_bits(0xbb6c4504cb1edff4),
    ],
    [
        f64::from_bits(0x3ebdb335a996d732),
        f64::from_bits(0x3b46a943d5a3ee38),
    ],
    [
        f64::from_bits(0x3eb7d4ad16dfb134),
        f64::from_bits(0x3b5b25308daf92e2),
    ],
    [
        f64::from_bits(0x3ecae97800b1ad43),
        f64::from_bits(0xbb2e6e6adfab5a3f),
    ],
    [
        f64::from_bits(0xbeb26020530152b5),
        f64::from_bits(0xbb4cb5914ec236ed),
    ],
    [
        f64::from_bits(0x3eb6aa2ec6fc1505),
        f64::from_bits(0xbaf91abbe5fc37f3),
    ],
    [
        f64::from_bits(0xbe8e955794a75596),
        f64::from_bits(0xbb2a281d8cdf613b),
    ],
    [
        f64::from_bits(0x3eae9b94b4bfa21d),
        f64::from_bits(0x3b470c89842b623c),
    ],
    [
        f64::from_bits(0x3e7bc5163ea8ae61),
        f64::from_bits(0x3b05f2b0982db0e4),
    ],
    [
        f64::from_bits(0x3e475ca101176aee),
        f64::from_bits(0xbae3d3c8d67b88cd),
    ],
    [
        f64::from_bits(0x3e1256e01de80a6e),
        f64::from_bits(0x3a901efb0d1aa0b1),
    ],
    [
        f64::from_bits(0x3ddb03432c85360d),
        f64::from_bits(0xba750127b61d0b1b),
    ],
    [
        f64::from_bits(0x3da2c0022103ca4c),
        f64::from_bits(0xba157d736f96e2f0),
    ],
    [
        f64::from_bits(0x3d68a17e736845f7),
        f64::from_bits(0x3a0052304d4cb211),
    ],
    [
        f64::from_bits(0x3d2eb988d0d47704),
        f64::from_bits(0x39b56226ee7f42a3),
    ],
    [
        f64::from_bits(0x3cf240d0d29d0683),
        f64::from_bits(0xb99e50b4b998bd92),
    ],
    [
        f64::from_bits(0x3cb4b6fc0ddc8c34),
        f64::from_bits(0x3952eddf425d81f1),
    ],
    [
        f64::from_bits(0x3c76823099fef7bc),
        f64::from_bits(0xb8fbfa709d41ba52),
    ],
    [
        f64::from_bits(0x3c37781aa77eece5),
        f64::from_bits(0xb8dd720fbe73365b),
    ],
    [
        f64::from_bits(0x3bf78751cb3ea19f),
        f64::from_bits(0xb86d54b4d612a2dc),
    ],
    [
        f64::from_bits(0x3bb6b88eb9b19162),
        f64::from_bits(0x3844849c0581dc04),
    ],
    [
        f64::from_bits(0x3b752a72ee02366d),
        f64::from_bits(0x37f70c849e5bb724),
    ],
    [
        f64::from_bits(0x3b3310c036e064af),
        f64::from_bits(0x37c8ab237479da58),
    ],
    [
        f64::from_bits(0x3af0ea2926b068d3),
        f64::from_bits(0x3785dbacb91566f6),
    ],
    [
        f64::from_bits(0x3aabd1a2274b9631),
        f64::from_bits(0xb734e61e72cd6369),
    ],
];

/// tgamma.c as_tgamma_accurate band ending at 4: leading coefficients.
pub(crate) const TG_ACC_CH4: [f64; 9] = [
    f64::from_bits(0x3ff7437000000000), // 0x1.7437000000000p+0
    f64::from_bits(0x3ff027b000000000), // 0x1.027b000000000p+0
    f64::from_bits(0x3fd9548000000000), // 0x1.9548000000000p-2
    f64::from_bits(0x3fbc558000000000), // 0x1.c558000000000p-4
    f64::from_bits(0x3f991a0000000000), // 0x1.91a0000000000p-6
    f64::from_bits(0x3f72900000000000), // 0x1.2900000000000p-8
    f64::from_bits(0x3f47c00000000000), // 0x1.7c00000000000p-11
    f64::from_bits(0x3f1a000000000000), // 0x1.a000000000000p-14
    f64::from_bits(0x3ef0000000000000), // 0x1.0000000000000p-16
];

/// tgamma.c as_tgamma_accurate band ending at 4: double-double tail.
pub(crate) const TG_ACC_CL4: [[f64; 2]; 26] = [
    [
        f64::from_bits(0x3ebe7866c657d7e3),
        f64::from_bits(0xbb5e572c42467bbe),
    ],
    [
        f64::from_bits(0xbecf681f0f0dd1b2),
        f64::from_bits(0x3b5214781d931745),
    ],
    [
        f64::from_bits(0x3ec92b4ede711c8c),
        f64::from_bits(0xbb4d65c1a367e3ff),
    ],
    [
        f64::from_bits(0xbea33d0927c13c96),
        f64::from_bits(0x3b46a79242c63d17),
    ],
    [
        f64::from_bits(0xbec197f189c3d621),
        f64::from_bits(0xbb54f1a82289c68f),
    ],
    [
        f64::from_bits(0xbe97452ecb747727),
        f64::from_bits(0x3b36005a038b51ac),
    ],
    [
        f64::from_bits(0xbea51f567dba1e03),
        f64::from_bits(0x3b217ebe5a14f803),
    ],
    [
        f64::from_bits(0x3eca5b7e360e27cd),
        f64::from_bits(0xbb10546204d2b0e6),
    ],
    [
        f64::from_bits(0xbec2e38e31f63f02),
        f64::from_bits(0x3b48cc3e369580e9),
    ],
    [
        f64::from_bits(0x3eb944636ddfd4a1),
        f64::from_bits(0xbb5cd9abdb0154f7),
    ],
    [
        f64::from_bits(0x3e858a8314ece20b),
        f64::from_bits(0x3b288bf6bd13a465),
    ],
    [
        f64::from_bits(0x3e510884c52a7f12),
        f64::from_bits(0x3aebc0b448873f4a),
    ],
    [
        f64::from_bits(0x3e192952062e7eb5),
        f64::from_bits(0xba9e0b1ce596988a),
    ],
    [
        f64::from_bits(0x3de172851a4b0c8c),
        f64::from_bits(0x3a8a5176b6c6c8fc),
    ],
    [
        f64::from_bits(0x3da6d6671a30ee9a),
        f64::from_bits(0x3a4e8d5ed2fcfc0e),
    ],
    [
        f64::from_bits(0x3d6c4e504af0c100),
        f64::from_bits(0xba0abb82f7703a39),
    ],
    [
        f64::from_bits(0x3d30b03339bb39c0),
        f64::from_bits(0xb9c1c99c30af694a),
    ],
    [
        f64::from_bits(0x3cf2bef701d4a3c5),
        f64::from_bits(0x399fdee26eac0983),
    ],
    [
        f64::from_bits(0x3cb42b6f1065ebca),
        f64::from_bits(0x3942f930bac677fa),
    ],
    [
        f64::from_bits(0x3c74be839a1e033a),
        f64::from_bits(0xb9188d939a249a33),
    ],
    [
        f64::from_bits(0x3c3498c43c164711),
        f64::from_bits(0xb8d23998cec39776),
    ],
    [
        f64::from_bits(0x3bf382547c29f33a),
        f64::from_bits(0xb894738c89c6e5ae),
    ],
    [
        f64::from_bits(0x3bb21e8ce6614723),
        f64::from_bits(0xb8577e521e4ba2df),
    ],
    [
        f64::from_bits(0x3b6f7692bdf0619c),
        f64::from_bits(0x380d7caee4bdb637),
    ],
    [
        f64::from_bits(0x3b2cc5367db7cbfc),
        f64::from_bits(0x37c5edbeed0867be),
    ],
    [
        f64::from_bits(0x3ae514eb3bdaa622),
        f64::from_bits(0xb772d38f68d85701),
    ],
];

/// tgamma.c fast path |x| < 1/4: double-double coefficients.
pub(crate) const TG_SMALL_CC: [[f64; 2]; 5] = [
    [
        f64::from_bits(0xbfe2788cfc6fb619),
        f64::from_bits(0x3c566d81dd231575),
    ],
    [
        f64::from_bits(0x3fefa658c23b1578),
        f64::from_bits(0x3c7dded15c22e35e),
    ],
    [
        f64::from_bits(0xbfed0a118f324b60),
        f64::from_bits(0xbc8bb37df476a7cc),
    ],
    [
        f64::from_bits(0x3fef6a51055097c6),
        f64::from_bits(0xbc830eee7e7c5482),
    ],
    [
        f64::from_bits(0xbfef6c80ec38bc47),
        f64::from_bits(0xbc722885891ee90d),
    ],
];

/// tgamma.c fast path |x| < 1/4: double coefficients.
pub(crate) const TG_SMALL_C: [f64; 16] = [
    f64::from_bits(0x3fefc7e0a6e9c2c9), // 0x1.fc7e0a6e9c2c9p-1
    f64::from_bits(0xbfefdf3f15764246), // -0x1.fdf3f15764246p-1
    f64::from_bits(0x3feff07b5af9892c), // 0x1.ff07b5af9892cp-1
    f64::from_bits(0xbfeff803d8f584c4), // -0x1.ff803d8f584c4p-1
    f64::from_bits(0x3feffc07f59b072b), // 0x1.ffc07f59b072bp-1
    f64::from_bits(0xbfeffe00e422ee2e), // -0x1.ffe00e422ee2ep-1
    f64::from_bits(0x3fefff102b561602), // 0x1.fff102b561602p-1
    f64::from_bits(0xbfefff9cb7b72f3b), // -0x1.fff9cb7b72f3bp-1
    f64::from_bits(0x3feffdcb35bbec92), // 0x1.ffdcb35bbec92p-1
    f64::from_bits(0xbfeffcc551b96878), // -0x1.ffcc551b96878p-1
    f64::from_bits(0x3ff013dde0ace169), // 0x1.013dde0ace169p+0
    f64::from_bits(0xbff01baffd0f7e86), // -0x1.01baffd0f7e86p+0
    f64::from_bits(0x3fee15c8c643ed7a), // 0x1.e15c8c643ed7ap-1
    f64::from_bits(0xbfeda0418fdfaac3), // -0x1.da0418fdfaac3p-1
    f64::from_bits(0x3ff665b8c5abe550), // 0x1.665b8c5abe550p+0
    f64::from_bits(0xbff721c7bc0d07c0), // -0x1.721c7bc0d07c0p+0
];

/// tgamma.c fast path 1/4 <= |x| <= 4 (around 3.5): double-double coefficients.
pub(crate) const TG_MID_CC: [[f64; 2]; 18] = [
    [
        f64::from_bits(0x400a96390899a074),
        f64::from_bits(0xbc56e95430fab070),
    ],
    [
        f64::from_bits(0x400d545472146024),
        f64::from_bits(0x3c7c07f9774e12b3),
    ],
    [
        f64::from_bits(0x400491ad1cb98836),
        f64::from_bits(0x3ca51e26c4cfd792),
    ],
    [
        f64::from_bits(0x3ff4a0b6a8230929),
        f64::from_bits(0x3c9c1c6993b10594),
    ],
    [
        f64::from_bits(0x3fe0e5d232b95859),
        f64::from_bits(0x3c7d4248748dd78b),
    ],
    [
        f64::from_bits(0x3fc71d1672129fee),
        f64::from_bits(0x3c43b47c61245ee6),
    ],
    [
        f64::from_bits(0x3fabd2afde7e4816),
        f64::from_bits(0xbc325466b734902d),
    ],
    [
        f64::from_bits(0x3f8d8376e1031a16),
        f64::from_bits(0x3c22cd76af7fbb20),
    ],
    [
        f64::from_bits(0x3f6c9e94992c88c1),
        f64::from_bits(0x3bf5d7be78c93d16),
    ],
    [
        f64::from_bits(0x3f490ba7276a0c19),
        f64::from_bits(0xbbd6cad258076bb3),
    ],
    [
        f64::from_bits(0x3f249cfed9d63c8b),
        f64::from_bits(0x3b50a8ada0cff18d),
    ],
    [
        f64::from_bits(0x3efec018849c245b),
        f64::from_bits(0x3b9cea7c4e5e9d4f),
    ],
    [
        f64::from_bits(0x3ed65e5a18d31c17),
        f64::from_bits(0x3b712fc2f27069ec),
    ],
    [
        f64::from_bits(0x3eaca1890add8727),
        f64::from_bits(0x3b469c0fe53eb0fa),
    ],
    [
        f64::from_bits(0x3e8378b3b91f9033),
        f64::from_bits(0xbb1d62590f524392),
    ],
    [
        f64::from_bits(0x3e5432cdb3640fca),
        f64::from_bits(0xbae33987f0b3b6b6),
    ],
    [
        f64::from_bits(0x3e2f239fc9cf2155),
        f64::from_bits(0xbac8a95d04bfb2e4),
    ],
    [
        f64::from_bits(0x3dee3ea4e1366932),
        f64::from_bits(0xba25c950f5465458),
    ],
];

/// tgamma.c fast path 1/4 <= |x| <= 4: double coefficients.
pub(crate) const TG_MID_C: [f64; 18] = [
    f64::from_bits(0x400a96390899a074), // 0x1.a96390899a074p+1
    f64::from_bits(0x400d545472146024), // 0x1.d545472146024p+1
    f64::from_bits(0x400491ad1cb98836), // 0x1.491ad1cb98836p+1
    f64::from_bits(0x3ff4a0b6a8230929), // 0x1.4a0b6a8230929p+0
    f64::from_bits(0x3fe0e5d232b95859), // 0x1.0e5d232b95859p-1
    f64::from_bits(0x3fc71d1672129fee), // 0x1.71d1672129feep-3
    f64::from_bits(0x3fabd2afde7e4816), // 0x1.bd2afde7e4816p-5
    f64::from_bits(0x3f8d8376e1031a16), // 0x1.d8376e1031a16p-7
    f64::from_bits(0x3f6c9e94992c88c1), // 0x1.c9e94992c88c1p-9
    f64::from_bits(0x3f490ba7276a0c19), // 0x1.90ba7276a0c19p-11
    f64::from_bits(0x3f249cfed9d63c8b), // 0x1.49cfed9d63c8bp-13
    f64::from_bits(0x3efec018849c245b), // 0x1.ec018849c245bp-16
    f64::from_bits(0x3ed65e5a18d31c17), // 0x1.65e5a18d31c17p-18
    f64::from_bits(0x3eaca1890add8727), // 0x1.ca1890add8727p-21
    f64::from_bits(0x3e8378b3b91f9033), // 0x1.378b3b91f9033p-23
    f64::from_bits(0x3e5432cdb3640fca), // 0x1.432cdb3640fcap-26
    f64::from_bits(0x3e2f239fc9cf2155), // 0x1.f239fc9cf2155p-29
    f64::from_bits(0x3dee3ea4e1366932), // 0x1.e3ea4e1366932p-33
];

/// tgamma.c as_logd r1: 2^(-i/32) approximations.
pub(crate) const TG_LOG_R1: [f64; 33] = [
    f64::from_bits(0x3ff0000000000000), // 0x1.0000000000000p+0
    f64::from_bits(0x3fef508000000000), // 0x1.f508000000000p-1
    f64::from_bits(0x3feea4a000000000), // 0x1.ea4a000000000p-1
    f64::from_bits(0x3fedfca000000000), // 0x1.dfca000000000p-1
    f64::from_bits(0x3fed582000000000), // 0x1.d582000000000p-1
    f64::from_bits(0x3fecb72000000000), // 0x1.cb72000000000p-1
    f64::from_bits(0x3fec19a000000000), // 0x1.c19a000000000p-1
    f64::from_bits(0x3feb7f8000000000), // 0x1.b7f8000000000p-1
    f64::from_bits(0x3feae8a000000000), // 0x1.ae8a000000000p-1
    f64::from_bits(0x3fea550000000000), // 0x1.a550000000000p-1
    f64::from_bits(0x3fe9c4a000000000), // 0x1.9c4a000000000p-1
    f64::from_bits(0x3fe9374000000000), // 0x1.9374000000000p-1
    f64::from_bits(0x3fe8ace000000000), // 0x1.8ace000000000p-1
    f64::from_bits(0x3fe8258000000000), // 0x1.8258000000000p-1
    f64::from_bits(0x3fe7a12000000000), // 0x1.7a12000000000p-1
    f64::from_bits(0x3fe71f8000000000), // 0x1.71f8000000000p-1
    f64::from_bits(0x3fe6a0a000000000), // 0x1.6a0a000000000p-1
    f64::from_bits(0x3fe6248000000000), // 0x1.6248000000000p-1
    f64::from_bits(0x3fe5ab0000000000), // 0x1.5ab0000000000p-1
    f64::from_bits(0x3fe5342000000000), // 0x1.5342000000000p-1
    f64::from_bits(0x3fe4bfe000000000), // 0x1.4bfe000000000p-1
    f64::from_bits(0x3fe44e0000000000), // 0x1.44e0000000000p-1
    f64::from_bits(0x3fe3dea000000000), // 0x1.3dea000000000p-1
    f64::from_bits(0x3fe371a000000000), // 0x1.371a000000000p-1
    f64::from_bits(0x3fe3070000000000), // 0x1.3070000000000p-1
    f64::from_bits(0x3fe29ea000000000), // 0x1.29ea000000000p-1
    f64::from_bits(0x3fe2388000000000), // 0x1.2388000000000p-1
    f64::from_bits(0x3fe1d48000000000), // 0x1.1d48000000000p-1
    f64::from_bits(0x3fe172c000000000), // 0x1.172c000000000p-1
    f64::from_bits(0x3fe1130000000000), // 0x1.1130000000000p-1
    f64::from_bits(0x3fe0b56000000000), // 0x1.0b56000000000p-1
    f64::from_bits(0x3fe059c000000000), // 0x1.059c000000000p-1
    f64::from_bits(0x3fe0000000000000), // 0x1.0000000000000p-1
];

/// tgamma.c as_logd r2: 2^(-i/1024) approximations.
pub(crate) const TG_LOG_R2: [f64; 33] = [
    f64::from_bits(0x3ff0000000000000), // 0x1.0000000000000p+0
    f64::from_bits(0x3feffa7000000000), // 0x1.ffa7000000000p-1
    f64::from_bits(0x3feff4f000000000), // 0x1.ff4f000000000p-1
    f64::from_bits(0x3fefef6000000000), // 0x1.fef6000000000p-1
    f64::from_bits(0x3fefe9e000000000), // 0x1.fe9e000000000p-1
    f64::from_bits(0x3fefe45000000000), // 0x1.fe45000000000p-1
    f64::from_bits(0x3fefded000000000), // 0x1.fded000000000p-1
    f64::from_bits(0x3fefd94000000000), // 0x1.fd94000000000p-1
    f64::from_bits(0x3fefd3c000000000), // 0x1.fd3c000000000p-1
    f64::from_bits(0x3fefce4000000000), // 0x1.fce4000000000p-1
    f64::from_bits(0x3fefc8c000000000), // 0x1.fc8c000000000p-1
    f64::from_bits(0x3fefc34000000000), // 0x1.fc34000000000p-1
    f64::from_bits(0x3fefbdc000000000), // 0x1.fbdc000000000p-1
    f64::from_bits(0x3fefb84000000000), // 0x1.fb84000000000p-1
    f64::from_bits(0x3fefb2c000000000), // 0x1.fb2c000000000p-1
    f64::from_bits(0x3fefad4000000000), // 0x1.fad4000000000p-1
    f64::from_bits(0x3fefa7c000000000), // 0x1.fa7c000000000p-1
    f64::from_bits(0x3fefa24000000000), // 0x1.fa24000000000p-1
    f64::from_bits(0x3fef9cd000000000), // 0x1.f9cd000000000p-1
    f64::from_bits(0x3fef975000000000), // 0x1.f975000000000p-1
    f64::from_bits(0x3fef91e000000000), // 0x1.f91e000000000p-1
    f64::from_bits(0x3fef8c6000000000), // 0x1.f8c6000000000p-1
    f64::from_bits(0x3fef86f000000000), // 0x1.f86f000000000p-1
    f64::from_bits(0x3fef817000000000), // 0x1.f817000000000p-1
    f64::from_bits(0x3fef7c0000000000), // 0x1.f7c0000000000p-1
    f64::from_bits(0x3fef769000000000), // 0x1.f769000000000p-1
    f64::from_bits(0x3fef711000000000), // 0x1.f711000000000p-1
    f64::from_bits(0x3fef6ba000000000), // 0x1.f6ba000000000p-1
    f64::from_bits(0x3fef663000000000), // 0x1.f663000000000p-1
    f64::from_bits(0x3fef60c000000000), // 0x1.f60c000000000p-1
    f64::from_bits(0x3fef5b5000000000), // 0x1.f5b5000000000p-1
    f64::from_bits(0x3fef55e000000000), // 0x1.f55e000000000p-1
    f64::from_bits(0x3fef507000000000), // 0x1.f507000000000p-1
];

/// tgamma.c as_logd (low, high) of -log(r1[i]).
pub(crate) const TG_LOG_L1: [[f64; 2]; 33] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x0000000000000000),
    ],
    [
        f64::from_bits(0x3da9f5e440f128db),
        f64::from_bits(0x3f962d07ab000000),
    ],
    [
        f64::from_bits(0xbda527d64b444fa3),
        f64::from_bits(0x3fa62f483d000000),
    ],
    [
        f64::from_bits(0x3d83aff57187d0cf),
        f64::from_bits(0x3fb0a26721400000),
    ],
    [
        f64::from_bits(0xbd64634c201e2b9c),
        f64::from_bits(0x3fb62e04bc000000),
    ],
    [
        f64::from_bits(0xbdbd46364a8017c7),
        f64::from_bits(0x3fbbb9db70800000),
    ],
    [
        f64::from_bits(0xbdb882b6acb3f696),
        f64::from_bits(0x3fc0a29f69c00000),
    ],
    [
        f64::from_bits(0x3da5a5833aeff542),
        f64::from_bits(0x3fc368507da00000),
    ],
    [
        f64::from_bits(0xbdb3876d32b0cbf5),
        f64::from_bits(0x3fc62e4116c00000),
    ],
    [
        f64::from_bits(0x3daf5712171380e6),
        f64::from_bits(0x3fc8f41d56800000),
    ],
    [
        f64::from_bits(0x3dbfc0b2e87a92c1),
        f64::from_bits(0x3fcbb98bc4c00000),
    ],
    [
        f64::from_bits(0x3db44c7ceb2f93f2),
        f64::from_bits(0x3fce7f71f0800000),
    ],
    [
        f64::from_bits(0x3daa147c39e44eba),
        f64::from_bits(0x3fd0a2bfe2c00000),
    ],
    [
        f64::from_bits(0x3da36d8fc46707d1),
        f64::from_bits(0x3fd205afe0300000),
    ],
    [
        f64::from_bits(0xbda0fd8155ea5850),
        f64::from_bits(0x3fd3685b58900000),
    ],
    [
        f64::from_bits(0x3da8954f1c1b010f),
        f64::from_bits(0x3fd4cb42e1900000),
    ],
    [
        f64::from_bits(0xbdb5d0bcd7fa4afa),
        f64::from_bits(0x3fd62e3e78c00000),
    ],
    [
        f64::from_bits(0xbdbb0a96458bf187),
        f64::from_bits(0x3fd7912364700000),
    ],
    [
        f64::from_bits(0x3dbc543eab5348b9),
        f64::from_bits(0x3fd8f42299600000),
    ],
    [
        f64::from_bits(0xbda15143e5c177e1),
        f64::from_bits(0x3fda5711c7e00000),
    ],
    [
        f64::from_bits(0x3d93be09bf52475c),
        f64::from_bits(0x3fdbb9c3ceb00000),
    ],
    [
        f64::from_bits(0xbd79b3b32e71e21d),
        f64::from_bits(0x3fdd1cd255b00000),
    ],
    [
        f64::from_bits(0xbd98f02175f93786),
        f64::from_bits(0x3fde7fb067100000),
    ],
    [
        f64::from_bits(0xbdbc5fb374b7ddcf),
        f64::from_bits(0x3fdfe2980ec00000),
    ],
    [
        f64::from_bits(0xbdb8e174c5571bbd),
        f64::from_bits(0x3fe0a2aef3500000),
    ],
    [
        f64::from_bits(0x3dbfa33ff819b3ec),
        f64::from_bits(0x3fe15420d4900000),
    ],
    [
        f64::from_bits(0x3d923d2634096ca6),
        f64::from_bits(0x3fe2058ca7900000),
    ],
    [
        f64::from_bits(0x3d9c8afc264146b2),
        f64::from_bits(0x3fe2b7156ff00000),
    ],
    [
        f64::from_bits(0x3dae21780abaa301),
        f64::from_bits(0x3fe3686c62000000),
    ],
    [
        f64::from_bits(0x3db3d67aee28cdc4),
        f64::from_bits(0x3fe419f01cd00000),
    ],
    [
        f64::from_bits(0x3dbccd8a77731be8),
        f64::from_bits(0x3fe4cb504d680000),
    ],
    [
        f64::from_bits(0x3da0cc7dc4dbbcfd),
        f64::from_bits(0x3fe57cb333b80000),
    ],
    [
        f64::from_bits(0x3db1cf79abc9e3b4),
        f64::from_bits(0x3fe62e42fef80000),
    ],
];

/// tgamma.c as_logd (low, high) of -log(r2[i]).
pub(crate) const TG_LOG_L2: [[f64; 2]; 32] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x0000000000000000),
    ],
    [
        f64::from_bits(0x3db2ccace5b018a7),
        f64::from_bits(0x3f4641ef40000000),
    ],
    [
        f64::from_bits(0xbdb88a5cd275513a),
        f64::from_bits(0x3f5623d3f0000000),
    ],
    [
        f64::from_bits(0xbd90006a77b80a2d),
        f64::from_bits(0x3f60a45310000000),
    ],
    [
        f64::from_bits(0x3d881a0ebe451dd0),
        f64::from_bits(0x3f6627a998000000),
    ],
    [
        f64::from_bits(0x3da4297627f3b4ac),
        f64::from_bits(0x3f6bbc0150000000),
    ],
    [
        f64::from_bits(0x3dbafb8521676db1),
        f64::from_bits(0x3f70a0a0c8000000),
    ],
    [
        f64::from_bits(0x3db080b4c8bf43ca),
        f64::from_bits(0x3f736bc4a0000000),
    ],
    [
        f64::from_bits(0x3dabbcdc4ef244f5),
        f64::from_bits(0x3f762f5a48000000),
    ],
    [
        f64::from_bits(0xbdbeb4354215c794),
        f64::from_bits(0x3f78f36a44000000),
    ],
    [
        f64::from_bits(0xbdb020c23741371b),
        f64::from_bits(0x3f7bb7f4b8000000),
    ],
    [
        f64::from_bits(0xbdbff1289819f095),
        f64::from_bits(0x3f7e7cf9d4000000),
    ],
    [
        f64::from_bits(0x3db9b1383de1a3f4),
        f64::from_bits(0x3f80a13cde000000),
    ],
    [
        f64::from_bits(0x3d97fa1788e44213),
        f64::from_bits(0x3f82043a52000000),
    ],
    [
        f64::from_bits(0x3daf22c04fdaaa38),
        f64::from_bits(0x3f83677558000000),
    ],
    [
        f64::from_bits(0xbdbd9828c736de23),
        f64::from_bits(0x3f84caee08000000),
    ],
    [
        f64::from_bits(0xbdb41b9d79946440),
        f64::from_bits(0x3f862ea474000000),
    ],
    [
        f64::from_bits(0x3dbaced891ec8e07),
        f64::from_bits(0x3f879298b2000000),
    ],
    [
        f64::from_bits(0xbdbe4c5365e893ff),
        f64::from_bits(0x3f88f2be4e000000),
    ],
    [
        f64::from_bits(0x3dbe8d32fe7dc6f5),
        f64::from_bits(0x3f8a572dbe000000),
    ],
    [
        f64::from_bits(0xbdb3bf707f8ee0b7),
        f64::from_bits(0x3f8bb7cd50000000),
    ],
    [
        f64::from_bits(0xbdbc60b95a619b91),
        f64::from_bits(0x3f8d1cb84a000000),
    ],
    [
        f64::from_bits(0x3da64cbc2b83b45c),
        f64::from_bits(0x3f8e7dd224000000),
    ],
    [
        f64::from_bits(0xbda68543f75f32c6),
        f64::from_bits(0x3f8fe338fc000000),
    ],
    [
        f64::from_bits(0x3db421a5be17c2ec),
        f64::from_bits(0x3f90a266bb000000),
    ],
    [
        f64::from_bits(0xbdaf6b329a1da537),
        f64::from_bits(0x3f91534f84000000),
    ],
    [
        f64::from_bits(0xbda9a217f361c264),
        f64::from_bits(0x3f92065ff9000000),
    ],
    [
        f64::from_bits(0x3d73856e49eac8dd),
        f64::from_bits(0x3f92b78651000000),
    ],
    [
        f64::from_bits(0x3d8c6c3e72a945a1),
        f64::from_bits(0x3f9368cb54000000),
    ],
    [
        f64::from_bits(0xbdbdcfdc96d3a1c6),
        f64::from_bits(0x3f941a2f0d000000),
    ],
    [
        f64::from_bits(0x3d9a0da4813daf37),
        f64::from_bits(0x3f94cbb185000000),
    ],
    [
        f64::from_bits(0x3dbb4d3084ac1ad1),
        f64::from_bits(0x3f957d52c8000000),
    ],
];

/// tgamma.c as_sinpid (low, high) sin(pi i/128).
pub(crate) const TG_ST: [[f64; 2]; 65] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x0000000000000000),
    ],
    [
        f64::from_bits(0xbbfb1d63091a0130),
        f64::from_bits(0x3f992155f7a3667e),
    ],
    [
        f64::from_bits(0xbc2912bd0d569a90),
        f64::from_bits(0x3fa91f65f10dd814),
    ],
    [
        f64::from_bits(0xbc49a088a8bf6b2c),
        f64::from_bits(0x3fb2d52092ce19f6),
    ],
    [
        f64::from_bits(0xbc3e2718d26ed688),
        f64::from_bits(0x3fb917a6bc29b42c),
    ],
    [
        f64::from_bits(0x3c4a2704729ae56d),
        f64::from_bits(0x3fbf564e56a9730e),
    ],
    [
        f64::from_bits(0x3c513000a89a11e0),
        f64::from_bits(0x3fc2c8106e8e613a),
    ],
    [
        f64::from_bits(0x3c6531ff779ddac6),
        f64::from_bits(0x3fc5e214448b3fc6),
    ],
    [
        f64::from_bits(0xbc626d19b9ff8d82),
        f64::from_bits(0x3fc8f8b83c69a60b),
    ],
    [
        f64::from_bits(0xbc1af1439e521935),
        f64::from_bits(0x3fcc0b826a7e4f63),
    ],
    [
        f64::from_bits(0xbc642deef11da2c4),
        f64::from_bits(0x3fcf19f97b215f1b),
    ],
    [
        f64::from_bits(0x3c7824c20ab7aa9a),
        f64::from_bits(0x3fd111d262b1f677),
    ],
    [
        f64::from_bits(0xbc75d28da2c4612d),
        f64::from_bits(0x3fd294062ed59f06),
    ],
    [
        f64::from_bits(0x3c70c97c4afa2518),
        f64::from_bits(0x3fd4135c94176601),
    ],
    [
        f64::from_bits(0xbc1efdc0d58cf620),
        f64::from_bits(0x3fd58f9a75ab1fdd),
    ],
    [
        f64::from_bits(0xbc744b19e0864c5d),
        f64::from_bits(0x3fd7088530fa459f),
    ],
    [
        f64::from_bits(0xbc672cedd3d5a610),
        f64::from_bits(0x3fd87de2a6aea963),
    ],
    [
        f64::from_bits(0x3c66da81290bdbab),
        f64::from_bits(0x3fd9ef7943a8ed8a),
    ],
    [
        f64::from_bits(0x3c65b362cb974183),
        f64::from_bits(0x3fdb5d1009e15cc0),
    ],
    [
        f64::from_bits(0x3c56850e59c37f8f),
        f64::from_bits(0x3fdcc66e9931c45e),
    ],
    [
        f64::from_bits(0x3c5e0d891d3c6841),
        f64::from_bits(0x3fde2b5d3806f63b),
    ],
    [
        f64::from_bits(0xbc32ec1fc1b776b8),
        f64::from_bits(0x3fdf8ba4dbf89aba),
    ],
    [
        f64::from_bits(0xbc8a5a014347406c),
        f64::from_bits(0x3fe073879922ffee),
    ],
    [
        f64::from_bits(0xbc8ef23b69abe4f1),
        f64::from_bits(0x3fe11eb3541b4b23),
    ],
    [
        f64::from_bits(0x3c8b25dd267f6600),
        f64::from_bits(0x3fe1c73b39ae68c8),
    ],
    [
        f64::from_bits(0xbc85da743ef3770c),
        f64::from_bits(0x3fe26d054cdd12df),
    ],
    [
        f64::from_bits(0xbc6efcc626f74a6f),
        f64::from_bits(0x3fe30ff7fce17035),
    ],
    [
        f64::from_bits(0x3c7e3e25e3954964),
        f64::from_bits(0x3fe3affa292050b9),
    ],
    [
        f64::from_bits(0x3c68076a2cfdc6b3),
        f64::from_bits(0x3fe44cf325091dd6),
    ],
    [
        f64::from_bits(0x3c63c293edceb327),
        f64::from_bits(0x3fe4e6cabbe3e5e9),
    ],
    [
        f64::from_bits(0xbc875720992bfbb2),
        f64::from_bits(0x3fe57d69348ceca0),
    ],
    [
        f64::from_bits(0xbc7251b352ff2a37),
        f64::from_bits(0x3fe610b7551d2cdf),
    ],
    [
        f64::from_bits(0xbc8bdd3413b26456),
        f64::from_bits(0x3fe6a09e667f3bcd),
    ],
    [
        f64::from_bits(0x3c80d4ef0f1d915c),
        f64::from_bits(0x3fe72d0837efff96),
    ],
    [
        f64::from_bits(0xbc70f537acdf0ad7),
        f64::from_bits(0x3fe7b5df226aafaf),
    ],
    [
        f64::from_bits(0xbc76f420f8ea3475),
        f64::from_bits(0x3fe83b0e0bff976e),
    ],
    [
        f64::from_bits(0xbc82c5e12ed1336d),
        f64::from_bits(0x3fe8bc806b151741),
    ],
    [
        f64::from_bits(0x3c83d419a920df0b),
        f64::from_bits(0x3fe93a22499263fb),
    ],
    [
        f64::from_bits(0xbc830ee286712474),
        f64::from_bits(0x3fe9b3e047f38741),
    ],
    [
        f64::from_bits(0xbc7128bb015df175),
        f64::from_bits(0x3fea29a7a0462782),
    ],
    [
        f64::from_bits(0x3c39f630e8b6dac8),
        f64::from_bits(0x3fea9b66290ea1a3),
    ],
    [
        f64::from_bits(0xbc8926da300ffcce),
        f64::from_bits(0x3feb090a58150200),
    ],
    [
        f64::from_bits(0xbc8bc69f324e6d61),
        f64::from_bits(0x3feb728345196e3e),
    ],
    [
        f64::from_bits(0xbc8825a732ac700a),
        f64::from_bits(0x3febd7c0ac6f952a),
    ],
    [
        f64::from_bits(0xbc76e0b1757c8d07),
        f64::from_bits(0x3fec38b2f180bdb1),
    ],
    [
        f64::from_bits(0xbc52fb761e946603),
        f64::from_bits(0x3fec954b213411f5),
    ],
    [
        f64::from_bits(0xbc5e7b6bb5ab58ae),
        f64::from_bits(0x3feced7af43cc773),
    ],
    [
        f64::from_bits(0xbc84ef5295d25af2),
        f64::from_bits(0x3fed4134d14dc93a),
    ],
    [
        f64::from_bits(0x3c7457e610231ac2),
        f64::from_bits(0x3fed906bcf328d46),
    ],
    [
        f64::from_bits(0x3c883c37c6107db3),
        f64::from_bits(0x3feddb13b6ccc23c),
    ],
    [
        f64::from_bits(0xbc8014c76c126527),
        f64::from_bits(0x3fee212104f686e5),
    ],
    [
        f64::from_bits(0xbc616b56f2847754),
        f64::from_bits(0x3fee6288ec48e112),
    ],
    [
        f64::from_bits(0x3c8760b1e2e3f81e),
        f64::from_bits(0x3fee9f4156c62dda),
    ],
    [
        f64::from_bits(0x3c7e82c791f59cc2),
        f64::from_bits(0x3feed740e7684963),
    ],
    [
        f64::from_bits(0x3c752c7adc6b4989),
        f64::from_bits(0x3fef0a7efb9230d7),
    ],
    [
        f64::from_bits(0xbc7d7bafb51f72e6),
        f64::from_bits(0x3fef38f3ac64e589),
    ],
    [
        f64::from_bits(0x3c7562172a361fd3),
        f64::from_bits(0x3fef6297cff75cb0),
    ],
    [
        f64::from_bits(0x3c7ab256778ffcb6),
        f64::from_bits(0x3fef8764fa714ba9),
    ],
    [
        f64::from_bits(0xbc87a0a8ca13571f),
        f64::from_bits(0x3fefa7557f08a517),
    ],
    [
        f64::from_bits(0x3c81ec8668ecacee),
        f64::from_bits(0x3fefc26470e19fd3),
    ],
    [
        f64::from_bits(0xbc887df6378811c7),
        f64::from_bits(0x3fefd88da3d12526),
    ],
    [
        f64::from_bits(0x3c6521ecd0c67e35),
        f64::from_bits(0x3fefe9cdad01883a),
    ],
    [
        f64::from_bits(0xbc6c57bc2e24aa15),
        f64::from_bits(0x3feff621e3796d7e),
    ],
    [
        f64::from_bits(0xbc81354d4556e4cb),
        f64::from_bits(0x3feffd886084cd0d),
    ],
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x3ff0000000000000),
    ],
];

/// tgamma.c as_expd (low, high) 2^(i/32).
pub(crate) const TG_E0: [[f64; 2]; 32] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x3ff0000000000000),
    ],
    [
        f64::from_bits(0x3c8d73e2a475b465),
        f64::from_bits(0x3ff059b0d3158574),
    ],
    [
        f64::from_bits(0x3c98a62e4adc610b),
        f64::from_bits(0x3ff0b5586cf9890f),
    ],
    [
        f64::from_bits(0xbc96c51039449b3a),
        f64::from_bits(0x3ff11301d0125b51),
    ],
    [
        f64::from_bits(0xbc819041b9d78a76),
        f64::from_bits(0x3ff172b83c7d517b),
    ],
    [
        f64::from_bits(0x3c9e016e00a2643c),
        f64::from_bits(0x3ff1d4873168b9aa),
    ],
    [
        f64::from_bits(0x3c99b07eb6c70573),
        f64::from_bits(0x3ff2387a6e756238),
    ],
    [
        f64::from_bits(0x3c8612e8afad1255),
        f64::from_bits(0x3ff29e9df51fdee1),
    ],
    [
        f64::from_bits(0x3c86f46ad23182e4),
        f64::from_bits(0x3ff306fe0a31b715),
    ],
    [
        f64::from_bits(0xbc963aeabf42eae2),
        f64::from_bits(0x3ff371a7373aa9cb),
    ],
    [
        f64::from_bits(0x3c8ada0911f09ebc),
        f64::from_bits(0x3ff3dea64c123422),
    ],
    [
        f64::from_bits(0x3c489b7a04ef80d0),
        f64::from_bits(0x3ff44e086061892d),
    ],
    [
        f64::from_bits(0x3c7d4397afec42e2),
        f64::from_bits(0x3ff4bfdad5362a27),
    ],
    [
        f64::from_bits(0xbc807abe1db13cad),
        f64::from_bits(0x3ff5342b569d4f82),
    ],
    [
        f64::from_bits(0x3c96324c054647ad),
        f64::from_bits(0x3ff5ab07dd485429),
    ],
    [
        f64::from_bits(0xbc9383c17e40b497),
        f64::from_bits(0x3ff6247eb03a5585),
    ],
    [
        f64::from_bits(0xbc9bdd3413b26456),
        f64::from_bits(0x3ff6a09e667f3bcd),
    ],
    [
        f64::from_bits(0xbc816e4786887a99),
        f64::from_bits(0x3ff71f75e8ec5f74),
    ],
    [
        f64::from_bits(0xbc841577ee04992f),
        f64::from_bits(0x3ff7a11473eb0187),
    ],
    [
        f64::from_bits(0xbc9d4c1dd41532d8),
        f64::from_bits(0x3ff82589994cce13),
    ],
    [
        f64::from_bits(0x3c96e9f156864b27),
        f64::from_bits(0x3ff8ace5422aa0db),
    ],
    [
        f64::from_bits(0xbc675fc781b57ebc),
        f64::from_bits(0x3ff93737b0cdc5e5),
    ],
    [
        f64::from_bits(0x3c7c7c46b071f2be),
        f64::from_bits(0x3ff9c49182a3f090),
    ],
    [
        f64::from_bits(0xbc9d2f6edb8d41e1),
        f64::from_bits(0x3ffa5503b23e255d),
    ],
    [
        f64::from_bits(0x3c97a1cd345dcc81),
        f64::from_bits(0x3ffae89f995ad3ad),
    ],
    [
        f64::from_bits(0xbc75584f7e54ac3b),
        f64::from_bits(0x3ffb7f76f2fb5e47),
    ],
    [
        f64::from_bits(0x3c811065895048dd),
        f64::from_bits(0x3ffc199bdd85529c),
    ],
    [
        f64::from_bits(0x3c7503cbd1e949db),
        f64::from_bits(0x3ffcb720dcef9069),
    ],
    [
        f64::from_bits(0x3c82ed02d75b3707),
        f64::from_bits(0x3ffd5818dcfba487),
    ],
    [
        f64::from_bits(0xbc91a5cd4f184b5c),
        f64::from_bits(0x3ffdfc97337b9b5f),
    ],
    [
        f64::from_bits(0xbc9e9c23179c2893),
        f64::from_bits(0x3ffea4afa2a490da),
    ],
    [
        f64::from_bits(0x3c99d3e12dd8a18b),
        f64::from_bits(0x3fff50765b6e4540),
    ],
];

/// tgamma.c as_expd (low, high) 2^(i/1024).
pub(crate) const TG_E1: [[f64; 2]; 32] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x3ff0000000000000),
    ],
    [
        f64::from_bits(0xbc8d7c96f201bb2f),
        f64::from_bits(0x3ff002c605e2e8cf),
    ],
    [
        f64::from_bits(0xbc75e00e62d6b30d),
        f64::from_bits(0x3ff0058c86da1c0a),
    ],
    [
        f64::from_bits(0x3c7da93f90835f75),
        f64::from_bits(0x3ff0085382faef83),
    ],
    [
        f64::from_bits(0xbc84f6b2a7609f71),
        f64::from_bits(0x3ff00b1afa5abcbf),
    ],
    [
        f64::from_bits(0xbc6406ac4e81a645),
        f64::from_bits(0x3ff00de2ed0ee0f5),
    ],
    [
        f64::from_bits(0x3c9c1d0660524e08),
        f64::from_bits(0x3ff010ab5b2cbd11),
    ],
    [
        f64::from_bits(0xbc72b6aeb6176892),
        f64::from_bits(0x3ff0137444c9b5b5),
    ],
    [
        f64::from_bits(0x3c9b61299ab8cdb7),
        f64::from_bits(0x3ff0163da9fb3335),
    ],
    [
        f64::from_bits(0xbc7008eff5142bf9),
        f64::from_bits(0x3ff019078ad6a19f),
    ],
    [
        f64::from_bits(0x3c75e7626621eb5b),
        f64::from_bits(0x3ff01bd1e77170b4),
    ],
    [
        f64::from_bits(0xbc8c11f5239bf535),
        f64::from_bits(0x3ff01e9cbfe113ef),
    ],
    [
        f64::from_bits(0xbc82bf310fc54eb6),
        f64::from_bits(0x3ff02168143b0281),
    ],
    [
        f64::from_bits(0xbc9314aa16278aa3),
        f64::from_bits(0x3ff02433e494b755),
    ],
    [
        f64::from_bits(0xbc7082ef51b61d7e),
        f64::from_bits(0x3ff027003103b10e),
    ],
    [
        f64::from_bits(0x3c564cbba902ca27),
        f64::from_bits(0x3ff029ccf99d720a),
    ],
    [
        f64::from_bits(0xbc719083535b085d),
        f64::from_bits(0x3ff02c9a3e778061),
    ],
    [
        f64::from_bits(0xbc8b8db0e9dbd87e),
        f64::from_bits(0x3ff02f67ffa765e6),
    ],
    [
        f64::from_bits(0x3c9fea8d61ed6016),
        f64::from_bits(0x3ff032363d42b027),
    ],
    [
        f64::from_bits(0x3c9bc2ee8e5799ac),
        f64::from_bits(0x3ff03504f75ef071),
    ],
    [
        f64::from_bits(0x3c656811eeade11a),
        f64::from_bits(0x3ff037d42e11bbcc),
    ],
    [
        f64::from_bits(0xbc9f1a93c1b824d3),
        f64::from_bits(0x3ff03aa3e170aafe),
    ],
    [
        f64::from_bits(0x3c9b7c00e7b751da),
        f64::from_bits(0x3ff03d7411915a8a),
    ],
    [
        f64::from_bits(0x3c99dc3add8f9c02),
        f64::from_bits(0x3ff04044be896ab6),
    ],
    [
        f64::from_bits(0xbc90a31c1977c96e),
        f64::from_bits(0x3ff04315e86e7f85),
    ],
    [
        f64::from_bits(0x3c735bc86af4ee9a),
        f64::from_bits(0x3ff045e78f5640b9),
    ],
    [
        f64::from_bits(0x3c621cd53d5e8b66),
        f64::from_bits(0x3ff048b9b35659d8),
    ],
    [
        f64::from_bits(0xbc7e7992580447b0),
        f64::from_bits(0x3ff04b8c54847a28),
    ],
    [
        f64::from_bits(0x3c84c3793aa0d08d),
        f64::from_bits(0x3ff04e5f72f654b1),
    ],
    [
        f64::from_bits(0x3c979a8be239ca45),
        f64::from_bits(0x3ff051330ec1a03f),
    ],
    [
        f64::from_bits(0xbc9abcae24b819df),
        f64::from_bits(0x3ff0540727fc1762),
    ],
    [
        f64::from_bits(0x3c806c87433776c9),
        f64::from_bits(0x3ff056dbbebb786b),
    ],
];

/// tgamma.c as_expd exp polynomial.
pub(crate) const TG_EXP_C: [[f64; 2]; 5] = [
    [
        f64::from_bits(0x3f462e42fefa39ef),
        f64::from_bits(0x3bdabc9e3bf9d4d1),
    ],
    [
        f64::from_bits(0x3e8ebfbdff82c58e),
        f64::from_bits(0x3b2ec07243b4e585),
    ],
    [
        f64::from_bits(0x3dcc6b08d704a0bf),
        f64::from_bits(0x3a694bac118264d5),
    ],
    [
        f64::from_bits(0x3d03b2ab719edc2d),
        f64::from_bits(0x39ab530cee32e3de),
    ],
    [
        f64::from_bits(0x3c35d87fe98a5fc4),
        f64::from_bits(0xb8c63e85fdbde1ca),
    ],
];

/// tgamma.c as_lgamma_asym x > 11.5: Stirling series.
pub(crate) const TG_ASYM_BIG: [[f64; 2]; 8] = [
    [
        f64::from_bits(0x3fdacfe390c97d69),
        f64::from_bits(0x3c734acf208a22c4),
    ],
    [
        f64::from_bits(0x3fb5555555555555),
        f64::from_bits(0x3c531799ffbcdddb),
    ],
    [
        f64::from_bits(0xbf66c16c16c165a9),
        f64::from_bits(0x3c01eefaee02f690),
    ],
    [
        f64::from_bits(0x3f4a01a019ada522),
        f64::from_bits(0xbbd4d52971deb155),
    ],
    [
        f64::from_bits(0xbf4381377e3a546d),
        f64::from_bits(0x3befd1b354a8db62),
    ],
    [
        f64::from_bits(0x3f4b9486dc1c9886),
        f64::from_bits(0xbbe2dac4b8cca031),
    ],
    [
        f64::from_bits(0xbf5f3ecd8799f337),
        f64::from_bits(0x3bfda5dd745e3963),
    ],
    [
        f64::from_bits(0x3f76d399e5618390),
        f64::from_bits(0x3c115e3000de141a),
    ],
];

/// tgamma.c as_lgamma_asym x <= 11.5: Stirling series.
pub(crate) const TG_ASYM_SMALL: [[f64; 2]; 13] = [
    [
        f64::from_bits(0x3fdacfe390c97d69),
        f64::from_bits(0x3c7f06a157d44d5b),
    ],
    [
        f64::from_bits(0x3fb5555555555541),
        f64::from_bits(0x3c59d5fc10df4161),
    ],
    [
        f64::from_bits(0xbf66c16c16bfb733),
        f64::from_bits(0xbbf557d8fba9e97a),
    ],
    [
        f64::from_bits(0x3f4a01a01651819c),
        f64::from_bits(0xbbedd3c0f402122a),
    ],
    [
        f64::from_bits(0xbf438136b229bfb4),
        f64::from_bits(0xbbc879990edddc5f),
    ],
    [
        f64::from_bits(0x3f4b94c0472d00a0),
        f64::from_bits(0x3be215a15f7d9289),
    ],
    [
        f64::from_bits(0xbf5f619a122c3918),
        f64::from_bits(0x3bf13405abdba76d),
    ],
    [
        f64::from_bits(0x3f79edef47081644),
        f64::from_bits(0x3c1d9d833b12b9b0),
    ],
    [
        f64::from_bits(0xbf9bfc20185bf7cc),
        f64::from_bits(0xbc38aa555605e3b1),
    ],
    [
        f64::from_bits(0x3fc0e832a9372330),
        f64::from_bits(0x3c5871cbde1ab342),
    ],
    [
        f64::from_bits(0xbfe2beb46518ed4a),
        f64::from_bits(0xbc50298c44c99cee),
    ],
    [
        f64::from_bits(0x3ffe5717107e0999),
        f64::from_bits(0x3c75bdfe7ac38f81),
    ],
    [
        f64::from_bits(0xc0090c04fbd840a6),
        f64::from_bits(0xbc95d2fbfe47e148),
    ],
];
